import random

itemList = [
    "Adamantine Breastplate",
    "Adamantine Chain Shirt",
    "Adamantine Scale Mail",
    "Adamantine Half Plate",
    "Adamantine Ring Mail",
    "Adamantine Chain Mail",
    "Adamantine Plate",
    "Adamantine Splint",
    "Wings of Flying",
    "Dragon Scale Mail",
    "Dragon Scale Mail (Black)",
    "Belt of Fire Giant Strength",
    "Dragon Scale Mail (Blue)",
    "Dragon Scale Mail (Brass)",
    "Dragon Scale Mail (Bronze)",
    "Dragon Scale Mail (Copper)",
    "Dragon Scale Mail (Gold)",
    "Dragon Scale Mail (Green)",
    "Dragon Scale Mail (Red)",
    "Dragon Scale Mail (Silver)",
    "Dragon Scale Mail (White)",
    "Mithral Armor",
    "Mithral Chain Shirt",
    "Mithral Scale Mail",
    "Mithral Breastplate",
    "Mithral Half Plate",
    "Mithral Ring Mail",
    "Mithral Chain Mail",
    "Mithral Splint",
    "Belt of Cloud Giant Strength",
    "Potion of Poison Resistance",
    "Mithral Plate",
    "Bracers of Archery",
    "Plate Armor of Etherealness",
    "Clothes, Costume",
    "Helm of Teleportation",
    "Clothes, Travelers",
    "Shield of Missile Attraction",
    "Gloves of Swimming and Climbing",
    "Helm of Comprehending Languages",
    "Robe of Eyes",
    "Boots of the Winterlands",
    "Cloak of the Manta Ray",
    "Belt of Giant Strength",
    "Belt of Hill Giant Strength",
    "Belt of Frost Giant Strength",
    "Belt of Stone Giant Strength",
    "Belt of Storm Giant Strength",
    "Robe of Useful Items",
    "Robe of Stars",
    "Animated Shield",
    "Spellguard Shield",
    "Boots of Elvenkind",
    "Robe of the Archmagi",
    "Boots of Speed",
    "Cloak of Protection",
    "Glamoured Studded Leather",
    "Mantle of Spell Resistance",
    "Winged Boots",
    "Gauntlets of Ogre Power",
    "Belt of Dwarvenkind",
    "Clothes, Common",
    "Cloak of Displacement",
    "Helm of Brilliance",
    "Armor of Vulnerability",
    "Armor of Vulnerability (Bludgeoning)",
    "Armor of Vulnerability (Piercing)",
    "Armor of Vulnerability (Slashing)",
    "Half Plate Armor of Vulnerability (Bludgeoning)",
    "Half Plate Armor of Vulnerability (Piercing)",
    "Half Plate Armor of Vulnerability (Slashing)",
    "Hide Armor of Vulnerability (Bludgeoning)",
    "Hide Armor of Vulnerability (Piercing)",
    "Hide Armor of Vulnerability (Slashing)",
    "Leather Armor of Vulnerability (Bludgeoning)",
    "Leather Armor of Vulnerability (Piercing)",
    "Leather Armor of Vulnerability (Slashing)",
    "Padded Armor of Vulnerability (Bludgeoning)",
    "Padded Armor of Vulnerability (Piercing)",
    "Padded Armor of Vulnerability (Slashing)",
    "Splint Armor of Vulnerability (Bludgeoning)",
    "Ink Pen",
    "Rope, Hempen (50 feet)",
    "Splint Armor of Vulnerability (Piercing)",
    "Splint Armor of Vulnerability (Slashing)",
    "Studded Leather Armor of Vulnerability (Bludgeoning)",
    "Studded Leather Armor of Vulnerability (Piercing)",
    "Studded Leather Armor of Vulnerability (Slashing)",
    "Headband of Intellect",
    "Gauntlets of Ogre Power",
    "Bracers of Defense",
    "Cloak of Arachnida",
    "Hat of Disguise",
    "Boots of Levitation",
    "Dwarven Plate",
    "Boots of Striding and Springing",
    "Armor of Invulnerability",
    "Barrel",
    "Cloak of Elvenkind",
    "Robe of Scintillating Colors",
    "Elven Chain",
    "Elven Mail",
    "Elven Chain Shirt",
    "Robes",
    "Cloak of the Bat",
    "Cape of the Mountebank",
    "Clothes, Fine",
    "Demon Armor",
    "Eyes of the Eagle",
    "Slippers of Spider Climbing",
    "Gloves of Missile Snaring",
    "Grappling Hook",
    "Sack",
    "Armor of Resistance",
    "Helm of Telepathy",
    "Arrow-Catching Shield",
    "Spell Scroll",
    "Spell Scroll (0 - Cantrip)",
    "Spell Scroll (1st Level)",
    "Manual of Flesh Golems",
    "Spell Scroll (2nd Level)",
    "Spell Scroll (3rd Leve)",
    "Spell Scroll (4th Level)",
    "Spell Scroll (5th Level)",
    "Spell Scroll (6th Level)",
    "Manual of Iron Golems",
    "Mirror, Steel",
    "Spell Scroll (7th Level)",
    "Spell Scroll (8th Level)",
    "Spell Scroll (9th Level)",
    "Manual of Bodily Health",
    "Manual of Gainful Exercise",
    "Paper (one sheet)",
    "Tome of Clear Thought",
    "Manual of Golems",
    "Manual of clay Golems",
    "Manual of Stone Golems",
    "Manual of Quickness of Action",
    "Spellbook",
    "Book",
    "Tome of Leadership and Influence",
    "Case, Map or Scroll",
    "Crystal",
    "Oil of Sharpness",
    "Dust of Sneezing and Choking",
    "Universal Solvent",
    "Dust of Dryness",
    "Oil (flask)",
    "Poison, Basic (vial)",
    "Dust of Disappearance",
    "Backpack",
    "Pole (10-foot)",
    "Bead of Force",
    "Alchemist's Fire (flask)",
    "Keoghtom's Ointment",
    "Deck of Many Things",
    "Oil of Etherealness",
    "Marvelous Pigments",
    "Feed (per day)",
    "Perfume (vial)",
    "Sovereign Glue",
    "Scale, Merchant's",
    "Tent, Two-Person",
    "Bottle, Glass",
    "Pick, Miner's",
    "Saddle, Pack",
    "Spikes, Iron (10)",
    "Lamp",
    "Ball Bearings",
    "Soap",
    "Saddle, Military",
    "Flask or Tankard",
    "Rope Silk (50 feet)",
    "Basket",
    "Bag of Holding",
    "Three-Dragon Ante Set",
    "Mirror, Steel",
    "Iron Flask",
    "Vial",
    "Case, Crossbow Bolt",
    "Lantern, Bullseye",
    "Saddle, Riding",
    "Rod",
    "Ram, Portable",
    "Lantern, Hooded",
    "Sack",
    "Bag of Devouring",
    "Fishing Tackle",
    "Climber's Kit",
    "Bit and Bridle",
    "Pot, Iron",
    "Ladder (10 foot)",
    "Hourglass",
    "Saddlebags",
    "Bag of Tricks",
    "Bedroll",
    "Chalk (1 piece)",
    "Saddlebags",
    "Bell",
    "Jug or Pitcher",
    "Chain (10 feet)",
    "Waterskin",
    "Tinderbox",
    "Candle",
    "Hunting Trap",
    "Rope, Hempen (50 feet)",
    "Saddle, Exotic",
    "Bucket",
    "Pole (10-foot)",
    "Spyglass",
    "Blanket",
    "Ladder (10 foot)",
    "Crowbar",
    "Dice Set",
    "Parchment (one sheet)",
    "Lantern, Bullseye",
    "Lantern of Revealing",
    "Piton",
    "Chest",
    "Rations (1 day)",
    "Caltrops (bag of 20)",
    "Lock",
    "Ink (1 ounce bottle)",
    "Torch",
    "Pouch",
    "Handy Haversack",
    "Horseshoes of a Zephyr",
    "Rope of Climbing",
    "Rope of Entanglement",
    "Horns of Valhalla",
    "Horn of Valhalla (Silver)",
    "Horn of Valhalla (Brass)",
    "Ring of Animal Influence",
    "Horn of Valhalla (Bronze)",
    "Horn of Valhalla (Iron)",
    "Viol",
    "Pan Flute",
    "Instrument of the Bards",
    "Ollamh Harp",
    "Anstruth Harp",
    "Horn of Blasting",
    "Ring of Poison Resistance",
    "Potter's Tools",
    "Canaith Mandolin",
    "Cli Lyre",
    "Doss Lute",
    "Fochlucan Bandore",
    "Ring of Fire Elemental Command",
    "Stone of Good Luck (Luckstone)",
    "Mac-Fuirmidh Cittern",
    "Horn",
    "Pipes of Haunting",
    "Lyre",
    "Drum",
    "Chime of Opening",
    "Pipes of the Sewers",
    "Shawm",
    "Signal Whistle",
    "Flute",
    "Lute",
    "Dulcimer",
    "Bagpipes",
    "Herbalism Kit",
    "Rings of Resistance",
    "Ring of Acid Resistance",
    "Ring of Cold Resistance",
    "Ring of Fire Resistance",
    "Ring of Force Resistance",
    "Ring of Lightning Resistance",
    "Ring of Necrotic Resistance",
    "Ring of Poison Resistance",
    "Ring of Psychic Resistance",
    "Ring of Radiant Resistance",
    "Ring of Thunder Resistance",
    "Ring of Swimming",
    "Ring of Earth Elemental Command",
    "Signet Ring",
    "Ring of Telekinesis",
    "Talisman of the Sphere",
    "Elemental Gems",
    "Elemental Gem (Blue Sapphire)",
    "Elemental Gem (Yellow Diamond)",
    "Elemental Gem (Red Corundum)",
    "Elemental Gem (Emerald)",
    "Necklace of Prayer Beads",
    "Amulet of Proof against Detection and Location",
    "Gem of Seeing",
    "Ring of Invisibility",
    "Ring of Mind Shielding",
    "Ring of the Ram",
    "Circlet of Blasting",
    "Ring of Spell Storing",
    "Amulet of Health",
    "Periapt of Wound Closure",
    "Periapt of Health",
    "Ring of Psychic Resistance",
    "Scarab of Protection",
    "Ring of Force Resistance",
    "Ring of Thunder Resistance",
    "Ring of Air Elemental Command",
    "Talisman of Pure Good",
    "Ring of Warmth",
    "Ring of Protection",
    "Ring of Djinni Summoning",
    "Gem of Brightness",
    "Ring of Evasion",
    "Medallion of Thoughts",
    "Ring of Regeneration",
    "Ring of Jumping",
    "Crystal Ball of Mind Reading",
    "Crystal Ball of Telepathy",
    "Ring of Shooting Stars",
    "Ring of X-ray Vision",
    "Necklace of Adaptation",
    "Ring of Feather Falling",
    "Talisman of Ultimate Evil",
    "Ring of Spell Turning",
    "Necklace of Fireballs",
    "Ring of Cold Resistance",
    "Ring of Three Wishes",
    "Ring of Free Action",
    "Amulet",
    "Pearl of Power",
    "Ring of Necrotic Resistance",
    "Brooch of Shielding",
    "Ring of Water Elemental Command",
    "Periapt of Proof against Poison",
    "Ring of Water Walking",
    "Ring of Elemental Command",
    "Ring of Acid Resistance",
    "Camel",
    "Elephant",
    "Warhorse",
    "Draft Horse",
    "Broom of Flying",
    "Donkey (or Mule)",
    "pony",
    "Riding Horse",
    "Goggles of Night",
    "Figurines of Wondrous Power",
    "Crystal Ball of True Seeing",
    "Figurine of Wondrous Power (Golden Lions)",
    "Figurine of Wondrous Power (Ebony Fly)",
    "Figurine of Wondrous Power (Obsidian Steed)",
    "Figurine of Wondrous Power (Serpentine Owl)",
    "Figurine of Wondrous Power (Marble Elephant)",
    "Abacus",
    "Occultant Abacus",
    "Figurine of Wondrous Power (Silver Raven)",
    "Figurine of Wondrous Power (Bronze Griffon)",
    "Figurine of Wondrous Power (Ivory Goats)",
    "Figurine of Wondrous Power (Onyx Dog)",
    "Instant Fortress",
    "Sprig of Mistletoe",
    "Amulet of the Planes",
    "Cubic Gate",
    "Rod of Alertness",
    "Deck of Illusions",
    "Feather Token (Whip)",
    "Crystal Balls",
    "Antitoxin",
    "Potion of Fire Resistance",
    "Sphere of Annihilation",
    "Feather Tokens",
    "Feather Token (Anchor)",
    "Feather Token (Bird)",
    "Feather Token (Fan)",
    "Feather Token (Swan Boat)",
    "Feather Token (Tree)",
    "Feather Token (Whip)",
    "Feather Token (Feather Fall)",
    "Reliquary",
    "Rod of Security",
    "Wind Fan",
    "Horseshoes of Speed",
    "Holy Water (flask)",
    "Bag of Beans",
    "Portable Hole",
    "Eversmoking Bottle",
    "Totem",
    "Mirror of Life Trapping",
    "Orb of Shielding (Psychic)",
    "Decanter of Endless Water",
    "Eyes of Charming",
    "Rod of Absorption",
    "Philter of Love",
    "Orb",
    "Orb of Direction",
    "Orb of Shielding (Acid and Poison)",
    "Orb of Shielding (Cold)",
    "Orb of Shielding (Fire)",
    "Orb of Shielding (Force)",
    "Orb of Shielding (Lightning and Thunder)",
    "Orb of Shielding (Necrotic)",
    "Orb of Shielding (Radiant)",
    "Orb of Shielding (Thunder)",
    "Orb of Time",
    "Orb of Dragonkind",
    "Murgaxor's Orb",
    "Bowl of Commanding Water Elementals",
    "Iron Bands of Binding",
    "Brazier of Commanding Fire Elementals",
    "Stone of Controlling Earth Elementals",
    "Cube of Force",
    "Immovable Rod",
    "Emblem",
    "Manacles",
    "Orb of Dragonkind",
    "Whetstone",
    "Dimensional Shackles",
    "Candle of Invocation",
    "Efreeti Bottle",
    "Ioun Stone of Greater Absorption",
    "Ioun Stone of Mastery",
    "Censer of Controlling Air Elementals",
    "Ioun Stone of Regeneration",
    "Ioun Stone of Absorption",
    "Ioun Stone of Agility",
    "Ioun Stone of Fortitude",
    "Ioun Stone of Insigh",
    "Ioun Stone of Intellect",
    "Ioun Stone of Leadership",
    "Playing Card Set",
    "Potion of Thunder Resistance",
    "Ioun Stone of Strength",
    "Ioun Stone of Vitality",
    "Ioun Stone of Awareness",
    "Ioun Stone of Protection",
    "Ioun Stone of Reserve",
    "Ioun Stone of Sustenance",
    "Rod of Rulership",
    "Eyes of Minute Seeing",
    "Well of Many Worlds",
    "Potion of Clairvoyance",
    "Potion of Vitality",
    "Potion of Diminution",
    "Potion of Force Resistance",
    "Potion of Water Breathing",
    "Potion of Invisibility",
    "Potion of Climbing",
    "Potions of Resistance",
    "Potion of Acid Resistance",
    "Potion of Cold Resistance",
    "Potion of Fire Resistance",
    "Potion of Force Resistance",
    "Potion of Lightning Resistance",
    "Potion of Poison Resistance",
    "Potion of Psychic Resistance",
    "Potion of Radiant Resistance",
    "Potion of Poison Resistance",
    "Potion of Thunder Resistance",
    "Potion of Gaseous Form",
    "Potion of Heroism",
    "Potion of Speed",
    "Potions of Healing",
    "Potion of Healing",
    "Potion of Healing (Greater)",
    "Potion of Healing (Superior)",
    "Potion of Healing (Supreme)",
    "Potion of Psychic Resistance",
    "Potion of Giant Strength",
    "Potion of Hill Giant Strength",
    "Potion of Frost Giant Strength",
    "Potion of Stone Giant Strength",
    "Potion of Fire Giant Strength",
    "Potion of Cloud Giant Strength",
    "Potion of Storm Giant Strength",
    "Potion of Cold Resistance",
    "Potion of Acid Resistance",
    "Potion of Animal Friendship",
    "Potion of Necrotic Resistance",
    "Potion of Poison",
    "Potion of Mind Reading",
    "Potion of Lightning Resistance",
    "Potion of Growth",
    "Poisoner's Kit",
    "Acid (vial)",
    "Potion of Flying",
    "Holy Water (flask)",
    "Barding",
    "Cartographer's Tools",
    "Glassblower's Tools",
    "Carpenter's Tools",
    "Navigator's Tools",
    "Mason's Tools",
    "Weavers Tools",
    "Forgery Kit",
    "Healer's Kit",
    "Dragonchess Set",
    "Alchemist's Supplies",
    "Mess Kit",
    "Cobbler's Tools",
    "Thieves' Tools",
    "Block and Tackle",
    "Smith's Tools",
    "Brewer's Supplies",
    "Disguise Kit",
    "Woodcarver's Tools",
    "Painter's Supplies",
    "Calligraphy's Supplies",
    "Tinker's Tools",
    "Shovel",
    "Sealing Wax",
    "Leatherworker's Tools",
    "Jeweler's Tools",
    "Cook's Utensils",
    "Component Pouch",
    "Longship",
    "Wagon",
    "Carpet of Flying",
    "Carpet of Flying (3 ft. x 5 ft.)",
    "Carpet of Flying (4 ft. x 6 ft.)",
    "Carpet of Flying (5 ft. x 7 ft.)",
    "Carpet of Flying (6 ft. x 9 ft.)",
    "Galley",
    "Chariot",
    "Carpets of Flying",
    "Carpet of Flying (3 ft. x 5 ft.)",
    "Carpet of Flying (4 ft. x 6 ft.)",
    "Carpet of Flying (5 ft. x 7 ft.)",
    "Carpet of Flying (6 ft. x 9 ft.)",
    "Apparatus of the Crab",
    "Sailing Ship",
    "Rowboat",
    "Carriage",
    "Folding Boat",
    "Sled",
    "Warship",
    "Keelboat",
    "Cart",
    "Staff of the Magi",
    "Staff of Swarming Insects",
    "Blowgun Needles, +1",
    "Blowgun Needles, +2",
    "Blowgun Needles, +3",
    "Staff of the Woodlands",
    "Sword of Life Stealing",
    "Greatsword of Life Stealing",
    "Longsword of Life Stealing",
    "Rapier of Life Stealing",
    "Scimitar of Life Stealing",
    "Shortsword of Life Stealing",
    "Blowgun Needles",
    "Berserker Axe",
    "Berserker Handaxe",
    "Berserker Battleaxe",
    "Berserker Greataxe",
    "Berserker Halberd",
    "Luck Blades",
    "Luck Blade Greatsword",
    "Luck Blade Longsword",
    "Luck Blade Rapier",
    "Luck Blade Scimitar",
    "Wand of the War Mage, +2",
    "Wand of the War Mage, +3",
    "Luck Blade Shortsword",
    "Wand of Magic Missiles",
    "Vicious Revolver",
    "Oathbow Longbow",
    "Oathbow Shortbow",
    "Efficient Quiver",
    "Vicious Trident",
    "Wands of the War Mage",
    "Wand of the War Mage, +1",
    "Trident of Fish Command",
    "Swords of Wounding",
    "Greatsword of Wounding",
    "Longsword of Wounding",
    "Rapier of Wounding",
    "Scimitar of Wounding",
    "Shortsword of Wounding",
    "Vorpal Swords",
    "Vorpal Greatsword",
    "Vorpal Longsword",
    "Vorpal Scimitar",
    "Vicious Dagger",
    "Vicious Club",
    "Frost Brand Scimitar",
    "Scimitar of Speed",
    "Dwarven Thrower",
    "Yew Wand",
    "Vicious Greatclub",
    "Staff of Frost",
    "Flame Tongues",
    "Flame Tongue Greatsword",
    "Flame Tongue Longsword",
    "Flame Tongue Rapier",
    "Flame Tongue Scimitar",
    "Flame Tongue Shortsword",
    "Holy Avenger",
    "Holy Avenger Greatsword",
    "Vicious Dagger",
    "Holy Avenger Longsword",
    "Holy Avenger Rapier",
    "Holy Avenger Scimitar",
    "Holy Avenger Shortsword",
    "Wand of Binding",
    "Vicious Weapons",
    "Longsword, +2",
    "Vicious Greatclub",
    "Vicious Handaxe",
    "Vicious Javelin",
    "Vicious Light Hammer",
    "Vicious Mace",
    "Vicious Quarterstaff",
    "Vicious Sickle",
    "Vicious Spear",
    "Vicious Yklwa",
    "Vicious Crossbow, Light",
    "Vicious Dart",
    "Vicious Shortbow",
    "Vicious Sling",
    "Vicious Battleaxe",
    "Vicious Flail",
    "Vicious Glaive",
    "Vicious Greataxe",
    "Vicious Greatsword",
    "Vicious Halberd",
    "Vicious Lance",
    "Vicious Longsword",
    "Vicious Maul",
    "Vicious Morningstar",
    "Vicious Pike",
    "Vicious Rapier",
    "Vicious Scimitar",
    "Vicious Shortsword",
    "Vicious Trident",
    "Vicious War Pick",
    "Vicious Warhammer",
    "Vicious Whip",
    "Vicious Blowgun",
    "Vicious Crossbow, Hand",
    "Vicious Crossbow, Heavy",
    "Vicious Longbow",
    "Vicious Net",
    "Vicious Pistol",
    "Vicious Musket",
    "Vicious Pistol, Automatic",
    "Vicious Revolver",
    "Vicious Rifle, Hunting",
    "Vicious Rifle, Automatic",
    "Vicious Shotgun",
    "Vicious Laser Pistol",
    "Vicious Antimatter Rifle",
    "Vicious Laser Rifle",
    "Swords of Sharpness",
    "Greatsword of Sharpness",
    "Longsword of Sharpness",
    "Scimitar of Sharpness",
    "Giant Slayers",
    "Giant Slayer Club",
    "Giant Slayer Dagger",
    "Giant Slayer Greatclub",
    "Giant Slayer Handaxe",
    "Giant Slayer Javelin",
    "Giant Slayer Light Hammer",
    "Giant Slayer Mace",
    "Giant Slayer Quarterstaff",
    "Giant Slayer Sickle",
    "Giant Slayer Spear",
    "Giant Slayer Dart",
    "Giant Slayer Light Crossbow",
    "Giant Slayer Shortbow",
    "Giant Slayer Sling",
    "Giant Slayer Battleaxe",
    "Giant Slayer Flail",
    "Giant Slayer Glaive",
    "Giant Slayer Greataxe",
    "Giant Slayer Greatsword",
    "Giant Slayer Halberd",
    "Giant Slayer Lance",
    "Giant Slayer Longsword",
    "Giant Slayer Maul",
    "Giant Slayer Morningstar",
    "Giant Slayer Pike",
    "Giant Slayer Rapier",
    "Giant Slayer Scimitar",
    "Giant Slayer Shortsword",
    "Giant Slayer Trident",
    "Giant Slayer Warhammer",
    "Giant Slayer War Pick",
    "Giant Slayer Whip",
    "Giant Slayer Blowgun",
    "Giant Slayer Hand Crossbow",
    "Giant Slayer Heavy Crossbow",
    "Giant Slayer Longbow",
    "Giant Slayer Musket",
    "Giant Slayer Pistol",
    "Giant Slayer Automatic Rifle",
    "Giant Slayer Hunting Rifle",
    "Giant Slayer Revolver",
    "Giant Slayer Semiautomatic Pistol",
    "Giant Slayer Shotgun",
    "Giant Slayer Antimatter Rifle",
    "Giant Slayer Laser Pistol",
    "Giant Slayer Laser Rifle",
    "Dragon Slayers",
    "Dragon Slayer Dragon Slayer Greatsword",
    "Dragon Slayer Longsword",
    "Dragon Slayer Rapier",
    "Dragon Slayer Scimitar",
    "Dragon Slayer Shortsword",
    "Staff of Fire",
    "Nine Lives Stealer Dart",
    "Nine Lives Stealer's",
    "Nine Lives Stealer Club",
    "Nine Lives Stealer Dagger",
    "Nine Lives Stealer Greatclub",
    "Nine Lives Stealer Handaxe",
    "Mace of Terror",
    "Nine Lives Stealer Javelin",
    "Nine Lives Stealer Light Hammer",
    "Nine Lives Stealer Mace",
    "Nine Lives Stealer Quarterstaff",
    "Nine Lives Stealer Sickle",
    "Nine Lives Stealer Spear",
    "Nine Lives Stealer Light Crossbow",
    "Nine Lives Stealer Shortbow",
    "Nine Lives Stealer Sling",
    "Nine Lives Stealer Battleaxe",
    "Nine Lives Stealer Flail",
    "Nine Lives Stealer Longsword",
    "Nine Lives Stealer Glaive",
    "Nine Lives Stealer Greataxe",
    "Nine Lives Stealer Greatsword",
    "Nine Lives Stealer Halberd",
    "Nine Lives Stealer Lance",
    "Wand of Fireballs",
    "Nine Lives Stealer Maul",
    "Nine Lives Stealer Morningstar",
    "Nine Lives Stealer Pike",
    "Nine Lives Stealer Rapier",
    "Nine Lives Stealer Scimitar",
    "Nine Lives Stealer Shortsword",
    "Staff of Withering",
    "Nine Lives Stealer Trident",
    "Nine Lives Stealer Warhammer",
    "Nine Lives Stealer War Pick",
    "Nine Lives Stealer Whip",
    "Nine Lives Stealer Blowgun",
    "Nine Lives Stealer Hand Crossbow",
    "Nine Lives Stealer Heavy Crossbow",
    "Nine Lives Stealer Longbow",
    "Nine Lives Stealer Musket",
    "Nine Lives Stealer Pistol",
    "Nine Lives Stealer Automatic Rifle",
    "Arrows",
    "Nine Lives Stealer Hunting Rifle",
    "Nine Lives Stealer Revolver",
    "Nine Lives Stealer Semiautomatic Pistol",
    "Nine Lives Stealer Shotgun",
    "Nine Lives Stealer ---",
    "Nine Lives Stealer Antimatter Rifle",
    "Nine Lives Stealer Laser Pistol",
    "Nine Lives Stealer Laser Rifle",
    "Swords of Wounding",
    "Greatsword of Wounding",
    "Longsword of Wounding",
    "Sling Bullets",
    "Rapier of Wounding",
    "Scimitar of Wounding",
    "Shortsword of Wounding",
    "--- of Wounding",
    "--- of Wounding",
    "--- of Wounding",
    "Frost Brand",
    "Frost Brand Greatsword",
    "Wand of Paralysis",
    "Quiver",
    "Frost Brand Longsword",
    "Frost Brand Rapier",
    "Frost Brand Scimitar",
    "Frost Brand Shortsword",
    "Frost Brand Glaive",
    "Wand of Enemy Detection",
    "Crossbow Bolts",
    "Staff of Thunder and Lightning",
    "Rod of Lordly Might",
    "Wand of Fear",
    "Wand of Secrets",
    "Hammer of Thunderbolts",
    "Wooden Staff",
    "Wand of the War Mage",
    "Arrow of Slaying",
    "Wand of Lightning Bolts",
    "Wand of Web",
    "Lance",
    "Lance, +1",
    "Lance, +2",
    "Lance, +3",
    "Wand of Polymorph",
    "Ram, Portable",
    "Hammer",
    "Hammer, Sledge",
    "Dagger of Venom",
    "Staff of Charming",
    "Wand of Wonder",
    "Mace of Smiting",
    "Staff of Healing",
    "Dancing Swords",
    "Dancing Greatsword",
    "Dancing Longsword",
    "Dancing Rapier",
    "Dancing Scimitar",
    "Dancing Shortsword",
    "Javelin of Lightning",
    "Wand of the War Mage, +1",
    "Wand of the War Mage, +2",
    "Wand of the War Mage, +3",
    "Sun Blade",
    "Dagger",
    "Longsword, +1",
    "Longsword, +2",
    "Longsword, +3",
    "Staff",
    "Staff of Power",
    "Defender",
    "Defender Greatsword",
    "Defender Longsword",
    "Defender Rapier",
    "Defender Scimitar",
    "Defender Shortsword",
    "Staff of Striking",
    "Wand",
    "Staff of the Python",
    "Wand of Paralysis",
    "Mace of Disruption"
]

# Randomly select one from the itemList
selected_item = random.choice(itemList)

# Output result
print(f"Class: {selected_item}")

