import os
import glob

path = "/Users/jasoncameron/Desktop/dnd_items/Items"
file = "/Users/jasoncameron/Desktop/dnd_items/Items/Staff of the Woodlands.md"

item_id_number = 1


# FINAL RUNNING FUNCTION

# FUN
# <F> Parse_Document
def Pars_Document(file):
    read_file = open(file, 'r')

    lines = Capture_Lines(read_file)

    item = Fill_In_Item(lines)  # Must be completed Prior to cond & magic bonuses

    item["has_charges"] = Search_Description_For_Word("charges", item["description"])
    item["magic_bonus_plus_1"] = Search_Description_For_Bonuses("+1", item["description"])
    item["magic_bonus_plus_2"] = Search_Description_For_Bonuses("+2", item["description"])
    item["magic_bonus_plus_3"] = Search_Description_For_Bonuses("+3", item["description"])

    conditions = Capture_Condition(item["description"])
    attached_spells = Capture_Attached_Spells(item["description"])
    item_tags = Capture_Tags(lines)
    item_types = Capture_Types(lines)


# <F> Capture_Lines
def Capture_Lines(input):
    lines = []
    for line in input:
        if line.strip() == "":
            continue
        else:
            lines.append(line.strip().replace("\xa0", ""))

    return lines


# <F> Capture_Types
def Capture_Types(lines):
    item_types = []

    for line in lines:
        if line.startswith("- "):
            mod_line = line.replace("- ", "")
            item_types.append(mod_line.lower().strip())

    return item_types


# <F> Capture_Tags
def Capture_Tags(lines):
    item_tags = []

    for line in lines:
        if line.startswith("item_tag:"):
            mod_line = line.replace("item_tag:", "")
            array_line = mod_line.split(",")
            for l in array_line:
                item_tags.append(l.lower().strip())

    return item_tags


# <F> Capture_Conditions
def Capture_Condition(item_description):
    item_conditions = []
    condition_list = ["blinded",
                      "charmed",
                      "deafened",
                      "exhaustion",
                      "frightened",
                      "grappled",
                      "incapacitated",
                      "invisible",
                      "paralyzed",
                      "petrified",
                      "poisoned",
                      "prone",
                      "restrained",
                      "stunned",
                      "unconscious"]

    mod_description = item_description.lower().replace("[", " ").replace("]", " ").replace(",", "").replace(".", "")
    array_description = mod_description.split(" ")

    for condition_word in condition_list:
        if condition_word in array_description:
            item_conditions.append(condition_word)

    return item_conditions


# <f> Search_Description_For_Word
def Search_Description_For_Word(searched_word, item_description):
    mod_description = item_description.lower().replace("[", " ").replace("]", " ").replace(",", "").replace(".", "")
    array_description = mod_description.split(" ")

    for word in array_description:
        if word == searched_word:
            return True
        else:
            return False


# <f> Search_Description_For_Bonuses
def Search_Description_For_Bonuses(searched_bonus, item_description):
    mod_description = item_description.lower().replace("[", " ").replace("]", " ").replace(",", "").replace(".", "")
    array_description = mod_description.split(" ")

    for word in array_description:
        if word == searched_bonus:
            index = array_description.index(word)
            next_word = array_description[index + 1]
            if next_word == "bonus":
                return True
    return False


# <F> Capture_Attached_Spells
def Capture_Attached_Spells(item_description):
    attached_spells = []
    spells = [
        "Druidcraft",
        "Regenerate",
        "Locate Creature",
        "Spare the Dying",
        "Circle of Power",
        "Power Word Kill",
        "Bless",
        "Harm",
        "Counterspell",
        "Polymorph",
        "Mage Armor",
        "Gentle Repose",
        "Fabricate",
        "Raise Dead",
        "Call Lightning",
        "Gate",
        "Mordenkainen’s Private Sanctum",
        "Phantasmal Force",
        "Beacon of Hope",
        "Produce Flame",
        "Transport via Plants",
        "Glyph of Warding",
        "Swift Quiver",
        "Fly",
        "Nondetection",
        "Sleep",
        "Sanctuary",
        "Speak with Plants",
        "Bestow Curse",
        "Reincarnate",
        "Hunter's Mark",
        "Misty Step",
        "Evard’s Black Tentacles",
        "Etherealness",
        "Flaming Sphere",
        "Plant Growth",
        "Arcane Eye",
        "Antipathy/Sympathy",
        "Conjure Fey",
        "Modify Memory",
        "Entangle",
        "Mass Suggestion",
        "Detect Evil and Good",
        "Dominate Beast",
        "Enhance Ability",
        "Blur",
        "Dispel Magic",
        "BLIGHT",
        "Eyebite",
        "Zone of Truth",
        "Poison Spray",
        "Hex",
        "Wall of Thorns",
        "Awaken",
        "True Polymorph",
        "Slow",
        "Hail of Thorns",
        "Hypnotic Pattern",
        "Banishing Smite",
        "Conjure Volley",
        "Guards and Wards",
        "Augury",
        "Animal Friendship",
        "Feeblemind",
        "Stone Shape",
        "Chill Touch",
        "Phantasmal Killer",
        "Mirror Image",
        "Detect Magic",
        "Dominate Monster",
        "Find Steed",
        "Holy Aura",
        "Maze",
        "Arcane Lock",
        "Divination",
        "Conjure Celestial",
        "Barkskin",
        "Arcane Gate",
        "Conjure Elemental",
        "Seeming",
        "Antimagic Field",
        "Animal Shapes",
        "Wind Walk",
        "Color Spray",
        "Pass without Trace",
        "Thorn Whip",
        "Prestidigitation",
        "Find Traps",
        "Globe of Invulnerability",
        "Magic Circle",
        "Dissonant Whispers",
        "Rary's Telepathic Bond",
        "Crown of Madness",
        "Leomund’s Secret Chest",
        "Finger of Death",
        "Resurrection",
        "Ray of Enfeeblement",
        "Banishment",
        "Teleportation Circle",
        "Create or Destroy Water",
        "Confusion",
        "Charm Person",
        "Grasping Vine",
        "Blade Ward",
        "Elemental Weapon",
        "Animate Objects",
        "Guidance",
        "Levitate",
        "Arms of Hadar",
        "Clone",
        "Feign Death",
        "Create Food and Water",
        "Shillelagh",
        "Calm Emotions",
        "Inflict Wounds",
        "Mending",
        "Illusory Script",
        "Control Water",
        "Cloudkill",
        "Meld into Stone",
        "Sleet Storm",
        "Comprehend Languages",
        "Word of Recall",
        "Imprisonment",
        "True Seeing",
        "Stinking Cloud",
        "Enthrall",
        "Fog Cloud",
        "Mirage Arcane",
        "Greater Restoration",
        "Protection from Energy",
        "Contagion",
        "Remove Curse",
        "Commune with Nature",
        "Nystul’s Magic Aura",
        "Minor Illusion",
        "Mind Blank",
        "Conjure Woodland Beings",
        "Weird",
        "Drawmij's Instant Summons",
        "Sequester",
        "Demiplane",
        "Grease",
        "Identify",
        "Haste",
        "Blindness/Deafness",
        "Aid",
        "Cordon of Arrows",
        "Storm of Vengeance",
        "Disguise Self",
        "Foresight",
        "Mage Hand",
        "Protection from Evil and Good",
        "True Strike",
        "Guardian of Faith",
        "Cloud of Daggers",
        "Silvery Barbs",
        "Tasha’s Hideous Laughter",
        "Locate Object",
        "Scrying",
        "Shield of Faith",
        "Magic Weapon",
        "Heroes' Feast",
        "Knock",
        "Command",
        "Friends",
        "Commune",
        "Animal Messenger",
        "Tree Stride",
        "Clairvoyance",
        "Contact Other Plane",
        "Locate Animals or Plants",
        "Bane",
        "Otto's Irresistible Dance",
        "Spirit Guardians",
        "Protection from Poison",
        "Time Stop",
        "Mislead",
        "Incendiary Cloud",
        "Mordenkainen’s Faithful Hound",
        "Legend Lore",
        "Creation",
        "Simulacrum",
        "Suggestion",
        "Wish",
        "Move Earth",
        "Teleport",
        "Animate Dead",
        "Death Ward",
        "Circle of Death",
        "Silent Image",
        "Dimension Door",
        "Zephyr Strike",
        "Find Familiar",
        "Planar Ally",
        "Ray of Sickness",
        "Vampiric Touch",
        "Hold Person",
        "Conjure Minor Elementals",
        "Silence",
        "Dominate Person",
        "Dispel Evil and Good",
        "Heat Metal",
        "Invisibility",
        "Freedom of Movement",
        "Web",
        "Magic Jar",
        "Programmed Illusion",
        "Rope Trick",
        "Thaumaturgy",
        "Speak with Dead",
        "Feather Fall",
        "Telekinesis",
        "Insect Plague",
        "Detect Poison and Disease",
        "Fear",
        "True Resurrection",
        "Flesh to Stone",
        "Armor of Agathys",
        "Phantom Steed",
        "Gaseous Form",
        "Vicious Mockery",
        "Speak with Animals",
        "Resistance",
        "Mordenkainen’s Magnificent Mansion",
        "Message",
        "Greater Invisibility",
        "Magic Mouth",
        "Spike Growth",
        "Enlarge/Reduce",
        "Darkvision",
        "Beast Sense",
        "Find the Path",
        "Symbol",
        "Stoneskin",
        "Dream",
        "Lesser Restoration",
        "Prismatic Wall",
        "Giant Insect",
        "Project Image",
        "Aura of Life",
        "Plane Shift",
        "Jump",
        "Astral Projection",
        "Blink",
        "Major Image",
        "Forbiddance",
        "Hallucinatory Terrain",
        "Reverse Gravity",
        "Acid Splash",
        "Goodberry",
        "Revivify",
        "Geas",
        "Create Undead",
        "Planar Binding",
        "Disintegrate",
        "Water Breathing",
        "Control Weather",
        "Detect Thoughts",
        "Ensnaring Strike",
        "Expeditious Retreat",
        "Tongues",
        "Tsunami",
        "Compelled Duel",
        "Shapechange",
        "Hold Monster",
        "Warding Bond",
        "Conjure Barrage",
        "Longstrider",
        "Shield",
        "Antilife Shell",
        "Alter Self",
        "See Invisibility",
        "Tenser’s Floating Disk",
        "Spider Climb",
        "Water Walk",
        "Compulsion",
        "Alarm",
        "Unseen Servant",
        "Lightning Arrow",
        "Glibness",
        "Heroism",
        "False Life",
        "Passwall",
        "Purify Food and Drink",
        "Power Word Stun",
        "Aura of Purity",
        "Conjure Animals"
    ]

    for spell in spells:
        if spell.lower() in item_description.replace("\n", "").replace(",", " ").replace("-", " ").replace("(",
                                                                                                           " ").lower():
            attached_spells.append(spell)

    if "Friends" in attached_spells and "Animal Friendship" in attached_spells:
        attached_spells.remove("Friends")

    if "Command" in attached_spells:
        array_description = item_description.lower().split(" ")
        index = array_description.index("command")
        next_word = array_description[index + 1].replace(",", "").replace("-", "").replace(".", "")
        if next_word == "word":
            attached_spells.remove("Command")

    return attached_spells


# <F> Capture Effects
def Capture_Effects(description_notes):
    effects = []
    effects_dictionary = {"Advantage": 1,
                          "vantage: Ability Checks": 2,
                          "vantage: Acrobatics": 3,
                          "vantage: Animal Handling": 4,
                          "vantage: Arcana": 5,
                          "vantage: Athletics": 6,
                          "vantage: Charisma Ability Checks": 7,
                          "vantage: Charisma Saving Throws": 8,
                          "vantage: Constitution Ability Checks": 9,
                          "advantage: Constitution Saving Throws": 10,
                          "advantage: Death Saving Throws": 11,
                          "advantage: Deception": 12,
                          "advantage: Dexterity Ability Checks": 13,
                          "advantage: Dexterity Attacks": 14,
                          "advantage: Dexterity Saving Throws": 15,
                          "advantage: History": 16,
                          "advantage: Initiative": 17,
                          "advantage: Insight": 18,
                          "advantage: Intelligence Ability Checks": 19,
                          "advantage: Intelligence Saving Throws": 20,
                          "advantage: Intimidation": 21,
                          "advantage: Investigation": 22,
                          "advantage: Medicine": 23,
                          "advantage: Melee Attacks": 24,
                          "advantage: Nature": 25,
                          "advantage: Perception": 26,
                          "advantage: Performance": 27,
                          "advantage: Persuasion": 28,
                          "advantage: Ranged Attacks": 29,
                          "advantage: Religion": 30,
                          "advantage: Saving Throws": 31,
                          "advantage: Sleight of Hand": 32,
                          "advantage: Spell Attacks": 33,
                          "advantage: Stealth": 34,
                          "advantage: Strength Ability Checks": 35,
                          "advantage: Strength Attacks": 36,
                          "advantage: Strength Saving Throws": 37,
                          "advantage: Survival": 38,
                          "advantage: Wisdom Ability Checks": 39,
                          "advantage: Wisdom Saving Throws": 40,
                          "Bonus": 41,
                          "Bonus: Ability Checks": 42,
                          "Bonus: Ability Score Maximum": 43,
                          "Bonus: AC Max Dex Modifier": 44,
                          "Bonus: Acrobatics": 45,
                          "Bonus: Animal Handling": 46,
                          "Bonus: Arcana": 47,
                          "Bonus: Armor Class": 48,
                          "Bonus: Armored Armor Class": 49,
                          "Bonus: Athletics": 50,
                          "Bonus: Charisma Ability Checks": 51,
                          "Bonus: Charisma Saving Throws": 52,
                          "Bonus: Charisma Score": 53,
                          "Bonus: Cleric Cantrip Damage": 54,
                          "Bonus: Constitution Ability Checks": 55,
                          "Bonus: Constitution Saving Throws": 56,
                          "Bonus: Constitution Score": 57,
                          "Bonus: Deception": 58,
                          "Bonus: Dexterity Ability Checks": 59,
                          "Bonus: Dexterity Attacks": 60,
                          "Bonus: Dexterity Saving Throws": 61,
                          "Bonus: Dexterity Score": 62,
                          "Bonus: Domain Spell": 63,
                          "Bonus: Dual Wield Armor Class": 64,
                          "Bonus: Eldritch Blast Damage": 65,
                          "Bonus: Extra Attacks": 66,
                          "Bonus: Half Proficiency": 67,
                          "Bonus: History": 68,
                          "Bonus: Hit Points": 69,
                          "Bonus: Hit Points per Level": 70,
                          "Bonus: Initiative": 71,
                          "Bonus: Insight": 72,
                          "Bonus: Intelligence Ability Checks": 73,
                          "Bonus: Intelligence Saving Throws": 74,
                          "Bonus: Intelligence Score": 75,
                          "Bonus: Intimidation": 76,
                          "Bonus: Investigation": 77,
                          "Bonus: Legendary Resistance": 78,
                          "Bonus: Magic": 79,
                          "Bonus: Magic Item Attack With Charisma": 80,
                          "Bonus: Magic Item Attack With Constitution": 81,
                          "Bonus: Magic Item Attack With Dexterity": 82,
                          "Bonus: Magic Item Attack With Intelligence": 83,
                          "Bonus: Magic Item Attack With Strength": 84,
                          "Bonus: Magic Item Attack With Wisdom": 85,
                          "Bonus: Medicine": 86,
                          "Bonus: Melee Attacks": 87,
                          "Bonus: Melee Reach": 88,
                          "Bonus: Melee Spell Attacks": 89,
                          "Bonus: Natural Attacks": 90,
                          "Bonus: Nature": 91,
                          "Bonus: Passive Investigation": 92,
                          "Bonus: Passive Perception": 93,
                          "Bonus: Perception": 94,
                          "Bonus: Performance": 95,
                          "Bonus: Persuasion": 96,
                          "Bonus: Proficiency": 97,
                          "Bonus: Proficiency Bonus": 98,
                          "Bonus: Ranged Attacks": 99,
                          "Bonus: Ranged Spell Attacks": 100,
                          "Bonus: Ranged Weapon Attacks": 101,
                          "Bonus: Religion": 102,
                          "Bonus: Saving Throws": 103,
                          "Bonus: Shield AC on Dex Saves": 104,
                          "Bonus: Slight of Hand": 105,
                          "Bonus: Seed": 106,
                          "Bonus: Seed (Burrowing)": 107,
                          "Bonus: Seed (Climbing)": 108,
                          "Bonus: Seed (Flying)": 109,
                          "Bonus: Seed (Swimming)": 110,
                          "Bonus: Seed (Walking)": 111,
                          "Bonus: Spell Attack Range Multiplier": 112,
                          "Bonus: Spell Attacks": 113,
                          "Bonus: Spell Group - Healing": 114,
                          "Bonus: Spell Save DC": 115,
                          "Bonus: Stealth": 116,
                          "Bonus: Strength Ability Checks": 117,
                          "Bonus: Strength Attacks": 118,
                          "Bonus: Strength Saving Throws": 119,
                          "Bonus: Strength Score": 120,
                          "Bonus: Survival": 121,
                          "Bonus: Temporary Hit Points": 122,
                          "Bonus: Twice Proficiency Bonus": 123,
                          "Bonus: Unarmed Attacks": 124,
                          "Bonus: Unarmored Armor Class": 125,
                          "Bonus: Unarmored Movement": 126,
                          "Bonus: Warlock Spell Attacks": 127,
                          "Bonus: Warlock Spell Save DC": 128,
                          "Bonus: Warlock Attack Range": 129,
                          "Bonus: Weapon Attack Range Multiplier": 130,
                          "Bonus: Wisdom Ability Checks": 131,
                          "Bonus: Wisdom Saving Throws": 132,
                          "Bonus: Wisdom Score": 133,
                          "Carrying Capacity": 134,
                          "Carrying Capacity: Gargantuan": 135,
                          "Carrying Capacity: Huge": 136,
                          "Carrying Capacity: Large": 137,
                          "Carrying Capacity: Medium": 138,
                          "Carrying Capacity: Multiplier": 139,
                          "Carrying Capacity: Small": 140,
                          "Carrying Capacity: Tiny": 141,
                          "Damage": 142,
                          "Damage: Acid": 143,
                          "Damage: Additional": 144,
                          "Damage: All": 145,
                          "Damage: Bludgeoning": 146,
                          "Damage: Cold": 147,
                          "Damage: Eldritch Blast": 148,
                          "Damage: Fire": 149,
                          "Damage: Force": 150,
                          "Damage: Lightning": 151,
                          "Damage: Longbow": 152,
                          "Damage: Melee Attacks": 153,
                          "Damage: Melee Weapon Attacks": 154,
                          "Damage: Natural Attacks": 155,
                          "Damage: Necrotic": 156,
                          "Damage: One-Handed Melee Attacks": 157,
                          "Damage: Piercing": 158,
                          "Damage: Poison": 159,
                          "Damage: Psychic": 160,
                          "Damage: Radiant": 161,
                          "Damage: Ranged Attacks": 162,
                          "Damage: Shortbow": 163,
                          "Damage: Slashing": 164,
                          "Damage: Thunder": 165,
                          "Damage: Unarmed Attacks": 167,
                          "Disadvantage": 168,
                          "Disadvantage: Ability Checks": 169,
                          "Disadvantage: Acrobatics": 170,
                          "Disadvantage: Animal Handling": 171,
                          "Disadvantage: Arcana": 172,
                          "Disadvantage: Athletics": 173,
                          "Disadvantage: Attack Rolls Against You": 174,
                          "Disadvantage: Charisma Ability Checks": 175,
                          "Disadvantage: Charisma Saving Throws": 176,
                          "Disadvantage: Constitution Ability Checks": 177,
                          "Disadvantage: Constitution Saving Throws": 178,
                          "Disadvantage: Death Saving Throws": 179,
                          "Disadvantage: Deception": 180,
                          "Disadvantage: Dexterity Ability Checks": 181,
                          "Disadvantage: Dexterity Attacks": 182,
                          "Disadvantage: Dexterity Saving Throws": 183,
                          "Disadvantage: History": 184,
                          "Disadvantage: Insight": 185,
                          "Disadvantage: Intelligence Ability Checks": 186,
                          "Disadvantage: Intelligence Saving Throws": 187,
                          "Disadvantage: Intimidation": 188,
                          "Disadvantage: Investigation": 189,
                          "Disadvantage: Medicine": 190,
                          "Disadvantage: Melee Attacks": 191,
                          "Disadvantage: Nature": 192,
                          "Disadvantage: Perception": 193,
                          "Disadvantage: Performance": 194,
                          "Disadvantage: Persuasion": 195,
                          "Disadvantage: Ranged Attacks": 196,
                          "Disadvantage: Religion": 197,
                          "Disadvantage: Saving Throws": 198,
                          "Disadvantage: Sleight of Hand": 199,
                          "Disadvantage: Spell Attacks": 200,
                          "Disadvantage: Stealth": 201,
                          "Disadvantage: Strength Ability Checks": 202,
                          "Disadvantage: Strength Attacks": 203,
                          "Disadvantage: Strength Saving Throws": 204,
                          "Disadvantage: Survival": 205,
                          "Disadvantage: Weapon Attacks": 206,
                          "Disadvantage: Wisdom Ability Checks": 207,
                          "Disadvantage: Wisdom Saving Throws": 208,
                          "Eldritch Blast": 209,
                          "Eldritch Blast: Bonus Damage": 210,
                          "Eldritch Blast: Bonus Range": 211,
                          "Expertise": 212,
                          "Expertise: Ability Checks": 213,
                          "Expertise: Acrobatics": 214,
                          "Expertise: Alchemist Supplies": 215,
                          "Expertise: Animal Handling": 216,
                          "Expertise: Arcana": 217,
                          "Expertise: Athletic": 218,
                          "Expertise: Bagpipes": 219,
                          "Expertise: Battleaxe": 220,
                          "Expertise: Blowgun": 221,
                          "Expertise: Breastplate": 222,
                          "Expertise: Brewer Supplies": 223,
                          "Expertise: Calligrapher Supplies": 224,
                          "Expertise: Carpenter Tools": 225,
                          "Expertise: Cartographer Tools": 226,
                          "Expertise: Chain Mail": 227,
                          "Expertise: Chain Shirt": 228,
                          "Expertise: Charisma Ability Checks": 229,
                          "Expertise: Charisma Saving Throws": 230,
                          "Expertise: Club": 231,
                          "Expertise: Cobbler Tools": 232,
                          "Expertise: Constitution Ability Checks": 233,
                          "Expertise: Constitution Saving Throws": 234,
                          "Expertise: Cook Utensils": 235,
                          "Expertise: Crossbow": 236,
                          "Expertise: Crossbow": 237,
                          "Expertise: Crossbow": 238,
                          "Expertise: Dagger": 239,
                          "Expertise: Dart": 240,
                          "Expertise: Deception": 241,
                          "Expertise: Dexterity Ability Checks": 242,
                          "Expertise: Dexterity Attacks": 243,
                          "Expertise: Dexterity Saving Throws": 244,
                          "Expertise: Dice Set": 245,
                          "Expertise: Disguise Kit": 246,
                          "Expertise: Drum": 247,
                          "Expertise: Dulcimer": 248,
                          "Expertise: Flail": 249,
                          "Expertise: Flute": 250,
                          "Expertise: Forgery Kit": 251,
                          "Expertise: Glaive": 252,
                          "Expertise: Glassblower Tools": 253,
                          "Expertise: Greataxe": 254,
                          "Expertise: Greatclub": 255,
                          "Expertise: Halberd": 256,
                          "Expertise: Half Plate": 257,
                          "Expertise: Handaxe": 258,
                          "Expertise: Heavy Armor": 259,
                          "Expertise: Herbalism Kit": 260,
                          "Expertise: Hid": 261,
                          "Expertise: History": 262,
                          "Expertise: Horn": 263,
                          "Expertise: Initiative": 264,
                          "Expertise: Insight": 265,
                          "Expertise: Intelligence Ability Checks": 266,
                          "Expertise: Intelligence Saving Throws": 267,
                          "Expertise: Intimidation": 268,
                          "Expertise: Investigation": 269,
                          "Expertise: Javelin": 270,
                          "Expertise: Jeweler Tools": 271,
                          "Expertise: Lance": 272,
                          "Expertise: Leather": 273,
                          "Expertise: Leatherworker Tools": 274,
                          "Expertise: Light Armor": 275,
                          "Expertise: Light Hammer": 276,
                          "Expertise: Longbow": 277,
                          "Expertise: Longsword": 278,
                          "Expertise: Lute": 279,
                          "Expertise: Lyre": 280,
                          "Expertise: Mace": 281,
                          "Expertise: Martial Weapons": 282,
                          "Expertise: Mason Tools": 283,
                          "Expertise: Maul": 284,
                          "Expertise: Medicine": 285,
                          "Expertise: Medium Armor": 286,
                          "Expertise: Melee Attacks": 287,
                          "Expertise: Mithril Plate Armor": 288,
                          "Expertise: Morningstar": 289,
                          "Expertise: Nature": 290,
                          "Expertise: Navigator Tools": 291,
                          "Expertise: Net": 292,
                          "Expertise: Padded": 293,
                          "Expertise: Painter Supplies": 294,
                          "Expertise: Pan Flute": 295,
                          "Expertise: Perception": 296,
                          "Expertise: Performance": 297,
                          "Expertise: Persuasion": 298,
                          "Expertise: Pike": 299,
                          "Expertise: Plate": 300,
                          "Expertise: Playing Card Set": 301,
                          "Expertise: Poisoner Kit": 302,
                          "Expertise: Potter Tools": 303,
                          "Expertise: Quarterstaff": 304,
                          "Expertise: Ranged Attacks": 305,
                          "Expertise: Rapier": 306,
                          "Expertise: Religion": 307,
                          "Expertise: Ring Mail": 308,
                          "Expertise: Saving Throws": 309,
                          "Expertise: Scale Mail": 310,
                          "Expertise: Scimitar": 311,
                          "Expertise: Shawn": 312,
                          "Expertise: Shortbow": 313,
                          "Expertise: Shortsword": 314,
                          "Expertise: Sickle": 315,
                          "Expertise: Simple Weapons": 316,
                          "Expertise: Sleight of Hand": 317,
                          "Expertise: Sling": 318,
                          "Expertise: Smith Tools": 319,
                          "Expertise: Spear": 320,
                          "Expertise: Spell Attacks": 321,
                          "Expertise: Splint": 322,
                          "Expertise: Stealth": 323,
                          "Expertise: Steel Shield": 324,
                          "Expertise: Strength Ability Checks": 325,
                          "Expertise: Strength Attacks": 326,
                          "Expertise: Strength Saving Throws": 327,
                          "Expertise: Studded Leather": 328,
                          "Expertise: Survival": 329,
                          "Expertise: Thieve Tools": 330,
                          "Expertise: Tinker Tools": 331,
                          "Expertise: Trident": 332,
                          "Expertise: Viol": 333,
                          "Expertise: War Pick": 334,
                          "Expertise: Warhammer": 335,
                          "Expertise: Weaver Tools": 336,
                          "Expertise: Whip": 337,
                          "Expertise: Wisdom Ability Checks": 338,
                          "Expertise: Wisdom Saving Throws": 339,
                          "Expertise: Woodcarver Tools": 340,
                          "Favored Enemy": 341,
                          "Favored Enemy: Aberrations": 342,
                          "Favored Enemy: Beasts": 343,
                          "Favored Enemy: Celestials": 344,
                          "Favored Enemy: Constructs": 345,
                          "Favored Enemy: Dragonborn": 346,
                          "Favored Enemy: Dragons": 347,
                          "Favored Enemy: Dwarves": 348,
                          "Favored Enemy: Elementals": 349,
                          "Favored Enemy: Elves": 350,
                          "Favored Enemy: Fey": 351,
                          "Favored Enemy: Fiends": 352,
                          "Favored Enemy: Giants": 353,
                          "Favored Enemy: Gnolls": 354,
                          "Favored Enemy: Gnomes": 355,
                          "Favored Enemy: Goblinoids": 356,
                          "Favored Enemy: Grimlock": 357,
                          "Favored Enemy: Halflings": 358,
                          "Favored Enemy: Humans": 359,
                          "Favored Enemy: Kobolds": 360,
                          "Favored Enemy: Lizardfolk": 361,
                          "Favored Enemy: Merfolk": 362,
                          "Favored Enemy: Monstrosities": 363,
                          "Favored Enemy: Oozes": 364,
                          "Favored Enemy: Orcs": 365,
                          "Favored Enemy: Plants": 366,
                          "Favored Enemy: Sahuagin": 367,
                          "Favored Enemy: Undead": 368,
                          "Favored Enemy: Werebears": 369,
                          "Favored Enemy: Wereboars": 370,
                          "Favored Enemy: Wererats": 371,
                          "Favored Enemy: Werewolves": 372,
                          "Feat": 373,
                          "Feat: Actor": 374,
                          "Feat: Alert": 375,
                          "Feat: Athlete": 376,
                          "Feat: Charger": 377,
                          "Feat: Choose a Feat": 378,
                          "Feat: Crossbow Expert": 379,
                          "Feat: Defensive Duelist": 380,
                          "Feat: Dual Wielder": 381,
                          "Feat: Dungeon Delver": 382,
                          "Feat: Durable": 383,
                          "Feat: Elemental Adept": 384,
                          "Feat: Grappler": 385,
                          "Feat: Great Weapon Master": 386,
                          "Feat: Healer": 387,
                          "Feat: Heavily Armored": 388,
                          "Feat: Heavy Armor Master": 389,
                          "Feat: Inspiring Leader": 390,
                          "Feat: Keen Mind": 391,
                          "Feat: Lightly Armored": 392,
                          "Feat: Linguist": 393,
                          "Feat: Lucky": 394,
                          "Feat: Mage Slayer": 395,
                          "Feat: Magic Initiate": 396,
                          "Feat: Martial Adept": 397,
                          "Feat: Medium Armor Master": 398,
                          "Feat: Mobile": 399,
                          "Feat: Moderately Armored": 400,
                          "Feat: Mounted Combatant": 401,
                          "Feat: Observant": 402,
                          "Feat: Polearm Master": 403,
                          "Feat: Resilient": 404,
                          "Feat: Ritual Caster": 405,
                          "Feat: Savage Attacker": 406,
                          "Feat: Sentinel": 407,
                          "Feat: Sharpshooter": 408,
                          "Feat: Shield Master": 409,
                          "Feat: Skilled": 410,
                          "Feat: Skulker": 411,
                          "Feat: Spell Sniper": 412,
                          "Feat: Svirfneblin Magic": 413,
                          "Feat: Tavern Brawler": 414,
                          "Feat: Tough": 415,
                          "Feat: War Caster": 416,
                          "Feat: Weapon Master": 417,
                          "Half Proficiency": 418,
                          "Half Proficiency: Ability Checks": 419,
                          "Half Proficiency: Acrobatics": 420,
                          "Half Proficiency: Alchemist Supplies": 421,
                          "Half Proficiency: Animal Handling": 422,
                          "Half Proficiency: Arcana": 423,
                          "Half Proficiency: Athletics": 424,
                          "Half Proficiency: Bagpipes": 425,
                          "Half Proficiency: Battleaxe": 426,
                          "Half Proficiency: Blowgun": 427,
                          "Half Proficiency: Breastplate": 428,
                          "Half Proficiency: Brewer Supplies": 429,
                          "Half Proficiency: Calligrapher Supplies": 430,
                          "Half Proficiency: Carpenter Tools": 431,
                          "Half Proficiency: Cartographer Tools": 432,
                          "Half Proficiency: Chain Mail": 433,
                          "Half Proficiency: Chain Shirt": 434,
                          "Half Proficiency: Charisma Ability Checks": 435,
                          "Half Proficiency: Charisma Saving Throws": 436,
                          "Half Proficiency: Club": 437,
                          "Half Proficiency: Cobbler Tools": 438,
                          "Half Proficiency: Constitution Ability Checks": 439,
                          "Half Proficiency: Constitution Saving Throws": 440,
                          "Half Proficiency: Cooking Utensils": 441,
                          "Half Proficiency: Crossbow": 442,
                          "Half Proficiency: Crossbow": 443,
                          "Half Proficiency: Crossbow": 444,
                          "Half Proficiency: Dagger": 445,
                          "Half Proficiency: Dart": 446,
                          "Half Proficiency: Deception": 447,
                          "Half Proficiency: Dexterity Ability Checks": 448,
                          "Half Proficiency: Dexterity  Attacks": 449,
                          "Half Proficiency: Dexterity Saving Throws": 450,
                          "Half Proficiency: Dice Set": 451,
                          "Half Proficiency: Disguise Kit": 452,
                          "Half Proficiency: Drum": 453,
                          "Half Proficiency: Dulcimer": 454,
                          "Half Proficiency: Flail": 455,
                          "Half Proficiency: Flute": 456,
                          "Half Proficiency: Forgery Kit": 457,
                          "Half Proficiency: Glaive": 458,
                          "Half Proficiency: Glassblower Tools": 459,
                          "Half Proficiency: Greataxe": 460,
                          "Half Proficiency: Greatclub": 461,
                          "Half Proficiency: Greatsword": 462,
                          "Half Proficiency: Halberd": 463,
                          "Half Proficiency: Half Plate": 464,
                          "Half Proficiency: Handaxe": 465,
                          "Half Proficiency: Heavy Armor": 466,
                          "Half Proficiency: Herbalism Kit": 467,
                          "Half Proficiency: Hide": 468,
                          "Half Proficiency: History": 469,
                          "Half Proficiency: Horn": 470,
                          "Half Proficiency: Initiative": 471,
                          "Half Proficiency: Insight": 472,
                          "Half Proficiency: Intelligence Ability Checks": 473,
                          "Half Proficiency: Intelligence Saving Throws": 474,
                          "Half Proficiency: Intimidation": 475,
                          "Half Proficiency: Investigation": 476,
                          "Half Proficiency: Javelin": 477,
                          "Half Proficiency: Jeweler Tools": 478,
                          "Half Proficiency: Lance": 479,
                          "Half Proficiency: Leather": 480,
                          "Half Proficiency: Leatherworker Tools": 481,
                          "Half Proficiency: Light Armor": 482,
                          "Half Proficiency: Light Hammer": 483,
                          "Half Proficiency: Longbow": 484,
                          "Half Proficiency: Longsword": 485,
                          "Half Proficiency: Lute": 486,
                          "Half Proficiency: Lyre": 487,
                          "Half Proficiency: Mace": 488,
                          "Half Proficiency: Martial Weapons": 489,
                          "Half Proficiency: Mason Tools": 490,
                          "Half Proficiency: Maul": 491,
                          "Half Proficiency: Medicine": 492,
                          "Half Proficiency: Medium Armor": 493,
                          "Half Proficiency: Melee Attacks": 494,
                          "Half Proficiency: Mithril Plate Armor": 495,
                          "Half Proficiency: Morningstar": 496,
                          "Half Proficiency: Nature": 497,
                          "Half Proficiency: Navigator Tools": 498,
                          "Half Proficiency: Net": 499,
                          "Half Proficiency: Padded": 500,
                          "Half Proficiency: Painter Supplies": 501,
                          "Half Proficiency: Pan Flute": 502,
                          "Half Proficiency: Perception": 503,
                          "Half Proficiency: Performance": 504,
                          "Half Proficiency: Persuasion": 505,
                          "Half Proficiency: Pike": 506,
                          "Half Proficiency: Plate": 507,
                          "Half Proficiency: Playing Card Set": 508,
                          "Half Proficiency: Poisoner Kit": 509,
                          "Half Proficiency: Potter Tools": 510,
                          "Half Proficiency: Quarterstaff": 511,
                          "Half Proficiency: Ranged Attacks": 512,
                          "Half Proficiency: Rapier": 513,
                          "Half Proficiency: Religion": 514,
                          "Half Proficiency: Ring Mail": 515,
                          "Half Proficiency: Round Up": 516,
                          "Half Proficiency: Saving Throws": 517,
                          "Half Proficiency: Scale Mail": 518,
                          "Half Proficiency: Scimitar": 519,
                          "Half Proficiency: Shawm": 520,
                          "Half Proficiency: Shortbow": 521,
                          "Half Proficiency: Shortsword": 522,
                          "Half Proficiency: Sickle": 523,
                          "Half Proficiency: Simple Weapons": 524,
                          "Half Proficiency: Sleight of Hand": 525,
                          "Half Proficiency: Sling": 526,
                          "Half Proficiency: Smith Tools": 527,
                          "Half Proficiency: Spear": 528,
                          "Half Proficiency: Spell Attacks": 529,
                          "Half Proficiency: Splint": 530,
                          "Half Proficiency: Stealth": 531,
                          "Half Proficiency: Steel Shield": 532,
                          "Half Proficiency: Strength Ability Checks": 533,
                          "Half Proficiency: Strength Attacks": 534,
                          "Half Proficiency: Strength Saving Throws": 535,
                          "Half Proficiency: Studded Leather": 536,
                          "Half Proficiency: Survival": 537,
                          "Half Proficiency: Thieve Tools": 538,
                          "Half Proficiency: Tinker Tools": 539,
                          "Half Proficiency: Trident": 540,
                          "Half Proficiency: Viol": 541,
                          "Half Proficiency: War Pick": 542,
                          "Half Proficiency: Warhammer": 543,
                          "Half Proficiency: Weaver Tools": 544,
                          "Half Proficiency: Whip": 545,
                          "Half Proficiency: Wisdom Ability Checks": 546,
                          "Half Proficiency: Wisdom Saving Throws": 547,
                          "Half Proficiency: Woodcarver Tools": 548,
                          "Half Proficiency Round up": 549,
                          "Half Proficiency Round up: Ability Checks": 550,
                          "Half Proficiency Round up: Acrobatics": 551,
                          "Half Proficiency Round up: Alchemist Supplies": 552,
                          "Half Proficiency Round up: Animal Handling": 553,
                          "Half Proficiency Round up: Arcana": 554,
                          "Half Proficiency Round up: Athletics": 555,
                          "Half Proficiency Round up: Bagpipes": 556,
                          "Half Proficiency Round up: Battleaxe": 557,
                          "Half Proficiency Round up: Blowgun": 558,
                          "Half Proficiency Round up: Breastplate": 559,
                          "Half Proficiency Round up: Brewer Supplies": 560,
                          "Half Proficiency Round up: Calligrapher Supplies": 561,
                          "Half Proficiency Round up: Carpenter Tools": 562,
                          "Half Proficiency Round up: Cartographer Tools": 563,
                          "Half Proficiency Round up: Chain Mail": 564,
                          "Half Proficiency Round up: Chain Shirt": 565,
                          "Half Proficiency Round up: Charisma Ability Checks": 566,
                          "Half Proficiency Round up: Charisma Saving Throws": 567,
                          "Half Proficiency Round up: Club": 568,
                          "Half Proficiency Round up: Cobbler Tools": 569,
                          "Half Proficiency Round up: Constitution Ability Checks": 570,
                          "Half Proficiency Round up: Constitution Saving Throws": 571,
                          "Half Proficiency Round up: Cooking Utensils": 572,
                          "Half Proficiency Round up: Crossbow": 573,
                          "Half Proficiency Round up: Crossbow": 574,
                          "Half Proficiency Round up: Crossbow": 575,
                          "Half Proficiency Round up: Dagger": 576,
                          "Half Proficiency Round up: Dart": 577,
                          "Half Proficiency Round up: Deception": 578,
                          "Half Proficiency Round up: Dexterity Ability Checks": 579,
                          "Half Proficiency Round up: Dexterity  Attacks": 580,
                          "Half Proficiency Round up: Dexterity Saving Throws": 581,
                          "Half Proficiency Round up: Dice Set": 582,
                          "Half Proficiency Round up: Disguise Kit": 583,
                          "Half Proficiency Round up: Drum": 584,
                          "Half Proficiency Round up: Dulcimer": 585,
                          "Half Proficiency Round up: Flail": 586,
                          "Half Proficiency Round up: Flute": 587,
                          "Half Proficiency Round up: Forgery Kit": 588,
                          "Half Proficiency Round up: Glaive": 589,
                          "Half Proficiency Round up: Glassblower Tools": 590,
                          "Half Proficiency Round up: Greataxe": 591,
                          "Half Proficiency Round up: Greatclub": 592,
                          "Half Proficiency Round up: Greatsword": 593,
                          "Half Proficiency Round up: Halberd": 594,
                          "Half Proficiency Round up: Half Plate": 595,
                          "Half Proficiency Round up: Handaxe": 596,
                          "Half Proficiency Round up: Heavy Armor": 597,
                          "Half Proficiency Round up: Herbalism Kit": 598,
                          "Half Proficiency Round up: Hide": 599,
                          "Half Proficiency Round up: History": 600,
                          "Half Proficiency Round up: Horn": 601,
                          "Half Proficiency Round up: Initiative": 602,
                          "Half Proficiency Round up: Insight": 603,
                          "Half Proficiency Round up: Intelligence Ability Checks": 604,
                          "Half Proficiency Round up: Intelligence Saving Throws": 605,
                          "Half Proficiency Round up: Intimidation": 606,
                          "Half Proficiency Round up: Investigation": 607,
                          "Half Proficiency Round up: Javelin": 608,
                          "Half Proficiency Round up: Jeweler Tools": 609,
                          "Half Proficiency Round up: Lance": 610,
                          "Half Proficiency Round up: Leather": 611,
                          "Half Proficiency Round up: Leatherworker Tools": 612,
                          "Half Proficiency Round up: Light Armor": 613,
                          "Half Proficiency Round up: Light Hammer": 614,
                          "Half Proficiency Round up: Longbow": 615,
                          "Half Proficiency Round up: Longsword": 616,
                          "Half Proficiency Round up: Lute": 617,
                          "Half Proficiency Round up: Lyre": 618,
                          "Half Proficiency Round up: Mace": 619,
                          "Half Proficiency Round up: Martial Weapons": 620,
                          "Half Proficiency Round up: Mason Tools": 621,
                          "Half Proficiency Round up: Maul": 622,
                          "Half Proficiency Round up: Medicine": 623,
                          "Half Proficiency Round up: Medium Armor": 624,
                          "Half Proficiency Round up: Melee Attacks": 625,
                          "Half Proficiency Round up: Mithril Plate Armor": 626,
                          "Half Proficiency Round up: Morningstar": 627,
                          "Half Proficiency Round up: Nature": 628,
                          "Half Proficiency Round up: Navigator Tools": 629,
                          "Half Proficiency Round up: Net": 630,
                          "Half Proficiency Round up: Padded": 631,
                          "Half Proficiency Round up: Painter Supplies": 632,
                          "Half Proficiency Round up: Pan Flute": 633,
                          "Half Proficiency Round up: Perception": 634,
                          "Half Proficiency Round up: Performance": 635,
                          "Half Proficiency Round up: Persuasion": 636,
                          "Half Proficiency Round up: Pike": 637,
                          "Half Proficiency Round up: Plate": 638,
                          "Half Proficiency Round up: Playing Card Set": 639,
                          "Half Proficiency Round up: Poisoner Kit": 640,
                          "Half Proficiency Round up: Potter Tools": 641,
                          "Half Proficiency Round up: Quarterstaff": 642,
                          "Half Proficiency Round up: Ranged Attacks": 643,
                          "Half Proficiency Round up: Rapier": 644,
                          "Half Proficiency Round up: Religion": 645,
                          "Half Proficiency Round up: Ring Mail": 646,
                          "Half Proficiency Round up: Round Up": 647,
                          "Half Proficiency Round up: Saving Throws": 648,
                          "Half Proficiency Round up: Scale Mail": 649,
                          "Half Proficiency Round up: Scimitar": 650,
                          "Half Proficiency Round up: Shawm": 651,
                          "Half Proficiency Round up: Shortbow": 652,
                          "Half Proficiency Round up: Shortsword": 653,
                          "Half Proficiency Round up: Sickle": 654,
                          "Half Proficiency Round up: Simple Weapons": 655,
                          "Half Proficiency Round up: Sleight of Hand": 656,
                          "Half Proficiency Round up: Sling": 657,
                          "Half Proficiency Round up: Smith Tools": 658,
                          "Half Proficiency Round up: Spear": 659,
                          "Half Proficiency Round up: Spell Attacks": 660,
                          "Half Proficiency Round up: Splint": 661,
                          "Half Proficiency Round up: Stealth": 662,
                          "Half Proficiency Round up: Steel Shield": 663,
                          "Half Proficiency Round up: Strength Ability Checks": 664,
                          "Half Proficiency Round up: Strength Attacks": 665,
                          "Half Proficiency Round up: Strength Saving Throws": 666,
                          "Half Proficiency Round up: Studded Leather": 667,
                          "Half Proficiency Round up: Survival": 668,
                          "Half Proficiency Round up: Thieve Tools": 669,
                          "Half Proficiency Round up: Tinker Tools": 670,
                          "Half Proficiency Round up: Trident": 671,
                          "Half Proficiency Round up: Viol": 672,
                          "Half Proficiency Round up: War Pick": 673,
                          "Half Proficiency Round up: Warhammer": 674,
                          "Half Proficiency Round up: Weaver Tools": 675,
                          "Half Proficiency Round up: Whip": 676,
                          "Half Proficiency Round up: Wisdom Ability Checks": 677,
                          "Half Proficiency Round up: Wisdom Saving Throws": 678,
                          "Half Proficiency Round up: Woodcarver Tools": 679,
                          "Ignore": 680,
                          "Ignore: Dual Wield Light Restrictions": 681,
                          "Ignore: Dual Wield Modifier Restrictions": 682,
                          "Ignore: Heavy Armor Speed Reduction": 683,
                          "Ignore: Unarmored Dex AC Bonus": 684,
                          "Ignore: Unarmored Dex Natural AC Bonus": 685,
                          "Ignore Weapon Property": 686,
                          "Ignore Weapon Property: Finesse": 687,
                          "Ignore Weapon Property: Heavy": 688,
                          "Ignore Weapon Property: Light": 689,
                          "Ignore Weapon Property: Loading": 690,
                          "Ignore Weapon Property: Range": 691,
                          "Ignore Weapon Property: Reach": 692,
                          "Ignore Weapon Property: Thrown": 693,
                          "Ignore Weapon Property: Two-Handed": 694,
                          "Ignore Weapon Property: Versatile": 695,
                          "Immunity": 696,
                          "Immunity: Acid": 697,
                          "Immunity: Blinded": 698,
                          "Immunity: Bludgeoning": 699,
                          "Immunity: Bludgeoning": 700,
                          "Immunity: Charmed": 701,
                          "Immunity: Cold": 702,
                          "Immunity: Critical Hits": 703,
                          "Immunity: Deafened": 704,
                          "Immunity: Disease": 705,
                          "Immunity: DO NO USE": 706,
                          "Immunity: Exhaustion": 707,
                          "Immunity: Fire": 708,
                          "Immunity: Force": 709,
                          "Immunity: Frightened": 710,
                          "Immunity: Grappled": 711,
                          "Immunity: Incapacitated": 712,
                          "Immunity: Invisible": 713,
                          "Immunity: Lightning": 714,
                          "Immunity: Magical Sleep": 715,
                          "Immunity: Necrotic": 716,
                          "Immunity: Paralyzed": 717,
                          "Immunity: Petrified": 718,
                          "Immunity: Piercing": 719,
                          "Immunity: Poison": 720,
                          "Immunity: Poisoned": 721,
                          "Immunity: Prone": 722,
                          "Immunity: Psychic": 723,
                          "Immunity: Radiant": 724,
                          "Immunity: Restrained": 725,
                          "Immunity: Slashing": 726,
                          "Immunity: Stunned": 727,
                          "Immunity: Thunder": 728,
                          "Immunity: Unconscious": 729,
                          "Kensei": 730,
                          "Kensei: Antimatter Rifle": 731,
                          "Kensei: Battleaxe": 732,
                          "Kensei: Blowgun": 733,
                          "Kensei: Boomerang": 734,
                          "Kensei: Club": 735,
                          "Kensei: Crossbow": 736,
                          "Kensei: Crossbow": 737,
                          "Kensei: Dagger": 738,
                          "Kensei: Dart": 739,
                          "Kensei: Double-Bladed Scimitar": 740,
                          "Kensei: Flail": 741,
                          "Kensei: Greatclub": 742,
                          "Kensei: Handaxe": 743,
                          "Kensei: Javelin": 744,
                          "Kensei: Laser Pistol": 745,
                          "Kensei: Laser Rifle": 746,
                          "Kensei: Light Hammer": 747,
                          "Kensei: Longbow": 748,
                          "Kensei: Longsword": 749,
                          "Kensei: Mace": 750,
                          "Kensei: Morningstar": 751,
                          "Kensei: Musket": 752,
                          "Kensei: Pistol": 753,
                          "Kensei: Pistol": 754,
                          "Kensei: Quarterstaff": 755,
                          "Kensei: Rapier": 756,
                          "Kensei: Revolver": 757,
                          "Kensei: Rifle": 758,
                          "Kensei: Rifle": 759,
                          "Kensei: Scimitar": 760,
                          "Kensei: Shortbow": 761,
                          "Kensei: Shortsword": 762,
                          "Kensei: Shotgun": 763,
                          "Kensei: Sickle": 764,
                          "Kensei: Sling": 765,
                          "Kensei: Spear": 766,
                          "Kensei: Trident": 767,
                          "Kensei: War Pick": 768,
                          "Kensei: Warhammer": 769,
                          "Kensei: Whip": 770,
                          "Kensei: Yklwa": 771,
                          "Language": 772,
                          "Language: Aarakocra": 773,
                          "Language: Abanasinian": 774,
                          "Language: Abyssal": 775,
                          "Language: All": 776,
                          "Language: Aquan": 777,
                          "Language: Auran": 778,
                          "Language: Blink Dog": 779,
                          "Language: Celestial": 780,
                          "Language: Common": 781,
                          "Language: Daelkyr": 782,
                          "Language: Deep Speech": 783,
                          "Language: Draconic": 784,
                          "Language: Druidic": 785,
                          "Language: Dwarvish": 786,
                          "Language: Elvish": 787,
                          "Language: Ergot": 788,
                          "Language: Giant": 789,
                          "Language: Giant Eagle": 790,
                          "Language: Giant Elk": 791,
                          "Language: Giant Owl": 792,
                          "Language: Gith": 793,
                          "Language: Gnoll": 794,
                          "Language: Gnomish": 795,
                          "Language: Goblin": 796,
                          "Language: Grippli": 797,
                          "Language: Grung": 798,
                          "Language: Hadozee": 799,
                          "Language: Halfling": 800,
                          "Language: Ignan": 801,
                          "Language: Infernal": 802,
                          "Language: Istarian": 803,
                          "Language: Kenderspeak": 804,
                          "Language: Kharolian": 805,
                          "Language: Khur": 806,
                          "Language: Kothian": 807,
                          "Language: Kraul": 808,
                          "Language: Leonin": 809,
                          "Language: Loxodon": 810,
                          "Language: Marquesian": 811,
                          "Language: Minotaur": 812,
                          "Language: Naush": 813,
                          "Language: Nerakese": 814,
                          "Language: Nordmaarian": 815,
                          "Language: Ogre": 816,
                          "Language: Orc": 817,
                          "Language: Otyugh": 818,
                          "Language: Primordial": 819,
                          "Language: Quori": 820,
                          "Language: Riedran": 821,
                          "Language: Sahuagin": 822,
                          "Language: Solamnic": 823,
                          "Language: Sphinx": 824,
                          "Language: Sylvan": 825,
                          "Language: Telepathy": 826,
                          "Language: Terran": 827,
                          "Language: Thieves Cant": 828,
                          "Language: Thri-Kreen": 829,
                          "Language: Undercommon": 830,
                          "Language: Vedalken": 831,
                          "Language: Winter Wolf": 832,
                          "Language: Worg": 833,
                          "Language: Yeti": 834,
                          "Language: Zemnian": 835,
                          "Melee Weapon Attack": 836,
                          "Melee Weapon Attack: Acid": 837,
                          "Melee Weapon Attack: Bludgeoning": 838,
                          "Melee Weapon Attack: Cold": 839,
                          "Melee Weapon Attack: Fire": 840,
                          "Melee Weapon Attack: Force": 841,
                          "Melee Weapon Attack: Lightning": 842,
                          "Melee Weapon Attack: Necrotic": 843,
                          "Melee Weapon Attack: Piercing": 844,
                          "Melee Weapon Attack: Poison": 845,
                          "Melee Weapon Attack: Psychic": 846,
                          "Melee Weapon Attack: Radiant": 847,
                          "Melee Weapon Attack: Slashing": 848,
                          "Melee Weapon Attack: Thunder": 849,
                          "Monk Weapon": 850,
                          "Monk Weapon: Battleaxe": 851,
                          "Monk Weapon: Blowgun": 852,
                          "Monk Weapon: Boomerang": 853,
                          "Monk Weapon: Club": 854,
                          "Monk Weapon: Crossbow": 855,
                          "Monk Weapon: Crossbow": 856,
                          "Monk Weapon: Crossbow": 857,
                          "Monk Weapon: Dagger": 858,
                          "Monk Weapon: Dart": 859,
                          "Monk Weapon: Flail": 860,
                          "Monk Weapon: Glaive": 861,
                          "Monk Weapon: Greataxe": 862,
                          "Monk Weapon: Greatsword": 863,
                          "Monk Weapon: Halberd": 864,
                          "Monk Weapon: Handaxe": 865,
                          "Monk Weapon: Javelin": 866,
                          "Monk Weapon: Lance": 867,
                          "Monk Weapon: Light Hammer": 868,
                          "Monk Weapon: Longbow": 869,
                          "Monk Weapon: Longsword": 870,
                          "Monk Weapon: Mace": 871,
                          "Monk Weapon: Maul": 872,
                          "Monk Weapon: Morningstar": 873,
                          "Monk Weapon: Net": 874,
                          "Monk Weapon: Pike": 875,
                          "Monk Weapon: Quarterstaff": 876,
                          "Monk Weapon: Rapier": 877,
                          "Monk Weapon: Scimitar": 878,
                          "Monk Weapon: Shortbow": 879,
                          "Monk Weapon: Shortsword": 880,
                          "Monk Weapon: Sickle": 881,
                          "Monk Weapon: Sling": 882,
                          "Monk Weapon: Spear": 883,
                          "Monk Weapon: Trident": 884,
                          "Monk Weapon: War Pick": 885,
                          "Monk Weapon: Warhammer": 886,
                          "Monk Weapon: Whip": 887,
                          "Monk Weapon: Yklwa": 888,
                          "Natural Weapon": 889,
                          "Natural Weapon: Bludgeoning": 890,
                          "Natural Weapon: Piercing": 891,
                          "Natural Weapon: Slashing": 892,
                          "Proficiency": 893,
                          "Proficiency: Ability Checks": 894,
                          "Proficiency: Acrobatics": 895,
                          "Proficiency: Alchemist Supplies": 896,
                          "Proficiency: Animal Handling": 897,
                          "Proficiency: Arcana": 898,
                          "Proficiency: Athletics": 899,
                          "Proficiency: Bagpipes": 900,
                          "Proficiency: Battleaxe": 901,
                          "Proficiency: Bird Pipes": 902,
                          "Proficiency: Blowgun": 903,
                          "Proficiency: Boomerang": 904,
                          "Proficiency: Breastplate": 905,
                          "Proficiency: Brewer Supplies": 906,
                          "Proficiency: Calligrapher Supplies": 907,
                          "Proficiency: Carpenter Tools": 908,
                          "Proficiency: Cartographer Tools": 909,
                          "Proficiency: Chain Mail": 910,
                          "Proficiency: Chain Shirt": 911,
                          "Proficiency: Charisma Ability Checks": 912,
                          "Proficiency: Charisma Saving Throws": 913,
                          "Proficiency: Choose a Bard Skill": 914,
                          "Proficiency: Club": 915,
                          "Proficiency: Cobbler Tools": 916,
                          "Proficiency: Constitution Ability Checks": 917,
                          "Proficiency: Constitution Saving Throws": 918,
                          "Proficiency: Cook Utensils": 919,
                          "Proficiency: Crossbow": 920,
                          "Proficiency: Crossbow": 921,
                          "Proficiency: Crossbow": 922,
                          "Proficiency: Dagger": 923,
                          "Proficiency: Dart": 924,
                          "Proficiency: Deception": 925,
                          "Proficiency: DELETE - double-Bladed Scimitar": 926,
                          "Proficiency: Dexterity Ability Checks": 927,
                          "Proficiency: Dexterity Attacks": 928,
                          "Proficiency: Dexterity Saving Throws": 929,
                          "Proficiency: Dice Set": 930,
                          "Proficiency: Disguise Kit": 931,
                          "Proficiency: Double-Bladed Scimitar": 932,
                          "Proficiency: Dragonchess Set": 933,
                          "Proficiency: Drum": 934,
                          "Proficiency: Dulcimer": 935,
                          "Proficiency: Firearms": 936,
                          "Proficiency: Flail": 937,
                          "Proficiency: Flute": 938,
                          "Proficiency: Forgery Kit": 939,
                          "Proficiency: Glaive": 940,
                          "Proficiency: Glassblower Tools": 941,
                          "Proficiency: Glaur": 942,
                          "Proficiency: Greataxe": 943,
                          "Proficiency: Greatclub": 944,
                          "Proficiency: Greatsword": 945,
                          "Proficiency: Halberd": 946,
                          "Proficiency: Half Plate": 947,
                          "Proficiency: Hand Drum": 948,
                          "Proficiency: Handaxe": 949,
                          "Proficiency: Heavy Armor": 950,
                          "Proficiency: Herbalism Kit": 951,
                          "Proficiency: Hide": 952,
                          "Proficiency: History": 953,
                          "Proficiency: Hoopak": 954,
                          "Proficiency: Hoopak (Ranged)": 955,
                          "Proficiency: Horn": 956,
                          "Proficiency: Improvised Weapon": 957,
                          "Proficiency: Initiative": 958,
                          "Proficiency: Insight": 959,
                          "Proficiency: Intelligence Ability Checks": 960,
                          "Proficiency: Intelligence Saving Throws": 961,
                          "Proficiency: Intimidation": 962,
                          "Proficiency: Investigation": 963,
                          "Proficiency: Javelin": 964,
                          "Proficiency: Jeweler Tools": 965,
                          "Proficiency: Lance": 966,
                          "Proficiency: Leather": 967,
                          "Proficiency: Leatherworker Tools": 968,
                          "Proficiency: Light Armor": 969,
                          "Proficiency: Light Hammer": 970,
                          "Proficiency: Longbow": 971,
                          "Proficiency: Longhorn": 972,
                          "Proficiency: Longsword": 973,
                          "Proficiency: Lute": 974,
                          "Proficiency: Lyre": 975,
                          "Proficiency: Mace": 976,
                          "Proficiency: Martial Weapons": 977,
                          "Proficiency: Mason Tools": 978,
                          "Proficiency: Maul": 979,
                          "Proficiency: Medicine": 980,
                          "Proficiency: Medium Armor": 981,
                          "Proficiency: Melee Attacks": 982,
                          "Proficiency: Mithril Plate Armor": 983,
                          "Proficiency: Morningstar": 984,
                          "Proficiency: Nature": 985,
                          "Proficiency: Navigator Tools": 986,
                          "Proficiency: Net": 987,
                          "Proficiency: Padded": 988,
                          "Proficiency: Painter Supplies": 989,
                          "Proficiency: Pan Flute": 990,
                          "Proficiency: Perception": 991,
                          "Proficiency: Performance": 992,
                          "Proficiency: Persuasion": 993,
                          "Proficiency: Pike": 994,
                          "Proficiency: Plate": 995,
                          "Proficiency: Playing Card Set": 996,
                          "Proficiency: Poisoner Kit": 997,
                          "Proficiency: Potter Tools": 998,
                          "Proficiency: Quarterstaff": 999,
                          "Proficiency: Ranged Attacks": 1000,
                          "Proficiency: Rapier": 1001,
                          "Proficiency: Religion": 1002,
                          "Proficiency: Ring Mail": 1003,
                          "Proficiency: Saving Throws": 1004,
                          "Proficiency: Scale Mail": 1005,
                          "Proficiency: Scimitar": 1006,
                          "Proficiency: Self": 1007,
                          "Proficiency: Shawm": 1008,
                          "Proficiency: Shields": 1009,
                          "Proficiency: Shortbow": 1010,
                          "Proficiency: Sickle": 1011,
                          "Proficiency: Simple Weapons": 1012,
                          "Proficiency: Sleight of Hand": 1013,
                          "Proficiency: Sling": 1014,
                          "Proficiency: Smith Tools": 1015,
                          "Proficiency: Songhorn": 1016,
                          "Proficiency: Spear": 1017,
                          "Proficiency: Spell Attacks": 1018,
                          "Proficiency: Splint": 1019,
                          "Proficiency: Stealth": 1020,
                          "Proficiency: Steel Shield": 1021,
                          "Proficiency: Strength Ability Checks": 1022,
                          "Proficiency: Strength Attacks": 1023,
                          "Proficiency: Strength Saving Throws": 1024,
                          "Proficiency: Studded Leather": 1025,
                          "Proficiency: Survival": 1026,
                          "Proficiency: Tantan": 1027,
                          "Proficiency: Thelarr": 1028,
                          "Proficiency: Thieves Tools": 1029,
                          "Proficiency: Three-Dragon Ante Set": 1030,
                          "Proficiency: Tinker Tools": 1031,
                          "Proficiency: Tocken": 1032,
                          "Proficiency: Trident": 1033,
                          "Proficiency: Vehicles (Land)": 1034,
                          "Proficiency: Vehicles (Space)": 1035,
                          "Proficiency: Vehicles (Water)": 1036,
                          "Proficiency: Viol": 1037,
                          "Proficiency: War Pick": 1038,
                          "Proficiency: Wargong": 1039,
                          "Proficiency: Warhammer": 1040,
                          "Proficiency: Weaver Tools": 1041,
                          "Proficiency: Whip": 1042,
                          "Proficiency: Whistle-Stick": 1043,
                          "Proficiency: Wisdom Ability Checks": 1044,
                          "Proficiency: Wisdom Saving Throws": 1045,
                          "Proficiency: Woodcarver Tools": 1046,
                          "Proficiency: Yarting": 1047,
                          "Proficiency: Yklwa": 1048,
                          "Proficiency: Zulkoon": 1049,
                          "protection": 1050,
                          "protection: 0 Hp": 1051,
                          "Ranged Weapon Attack": 1052,
                          "Ranged Weapon Attack: Acid": 1053,
                          "Ranged Weapon Attack: Bludgeoning": 1054,
                          "Ranged Weapon Attack: Cold": 1055,
                          "Ranged Weapon Attack: Fire": 1056,
                          "Ranged Weapon Attack: Force": 1057,
                          "Ranged Weapon Attack: Lightning": 1058,
                          "Ranged Weapon Attack: Necrotic": 1059,
                          "Ranged Weapon Attack: Piercing": 1060,
                          "Ranged Weapon Attack: Poison": 1061,
                          "Ranged Weapon Attack: Psychic": 1062,
                          "Ranged Weapon Attack: Radiant": 1063,
                          "Ranged Weapon Attack: Slashing": 1064,
                          "Ranged Weapon Attack: Thunder": 1065,
                          "Replace Damage Type": 1066,
                          "Replace Damage Type: Acid": 1067,
                          "Replace Damage Type: Bludgeoning": 1068,
                          "Replace Damage Type: Cold": 1069,
                          "Replace Damage Type: Fire": 1070,
                          "Replace Damage Type: Force": 1071,
                          "Replace Damage Type: Lightning": 1072,
                          "Replace Damage Type: Necrotic": 1073,
                          "Replace Damage Type: Piercing": 1074,
                          "Replace Damage Type: Poison": 1075,
                          "Replace Damage Type: Psychic": 1076,
                          "Replace Damage Type: Radiant": 1077,
                          "Replace Damage Type: Slashing": 1078,
                          "Replace Damage Type: Thunder": 1079,
                          "Resistance": 1080,
                          "Resistance: Acid": 1081,
                          "Resistance: All": 1082,
                          "Resistance: All Except Psychic": 1083,
                          "Resistance: Bludgeoning": 1084,
                          "Resistance: Bludgeoning": 1085,
                          "Resistance: Cold": 1086,
                          "Resistance: Damage Dealt by Traps": 1087,
                          "Resistance: Cod": 1088,
                          "Resistance: Damage Dealt by Traps": 1089,
                          "Resistance: Fire": 1090,
                          "Resistance: Force": 1091,
                          "Resistance: Lightning": 1092,
                          "Resistance: Necrotic": 1093,
                          "Resistance: Piercing": 1094,
                          "Resistance: Poison": 1095,
                          "Resistance: Psychic": 1096,
                          "Resistance: Radiant": 1097,
                          "Resistance: Ranged Attacks": 1098,
                          "Resistance: Slashing": 1099,
                          "Resistance: Thunder": 1100,
                          "Sense": 1101,
                          "Sense: Blindsight": 1102,
                          "Sense: Darkvision": 1103,
                          "Sense: Tremorsense": 1104,
                          "Sense: Truesight": 1105,
                          "Set": 1106,
                          "Set: Ability Score Maximum": 1107,
                          "Set: AC Max Dex Armored Modifier": 1108,
                          "Set: AC Max Dex Modifier": 1109,
                          "Set: AC Max Dex Unarmored Modifier": 1110,
                          "Set: Armor Cass": 1111,
                          "Set: Attunement Slots": 1112,
                          "Set: Charisma Score": 1113,
                          "Set: Constitution Score": 1114,
                          "Set: Death": 1115,
                          "Set: Dexterity Score": 1116,
                          "Set: Eldritch Blast Range": 1117,
                          "Set: Extra Attacks": 1118,
                          "Set: Innate Speed (Burrowing)": 1119,
                          "Set: Innate Speed (Climbing)": 1120,
                          "Set: Innate Speed (Flying)": 1121,
                          "Set: Innate Speed (Swimming)": 1122,
                          "Set: Innate Speed (Walking)": 1123,
                          "Set: Intelligence Score": 1124,
                          "Set: Minimum Base Armor": 1125,
                          "Set: Speed (Burrowing)": 1126,
                          "Set: Speed (Flying)": 1127,
                          "Set: Speed (Swimming)": 1128,
                          "Set: Speed (Walking)": 1129,
                          "Set: Strength Score": 1130,
                          "Set: Subclass": 1131,
                          "Set: Unarmed Damage Die": 1132,
                          "Set: Unarmored Armor Class": 1133,
                          "Set: Wisdom Score": 1134,
                          "Set Base": 1135,
                          "Set Base: Blindsight": 1136,
                          "Set Base: Darkvision": 1137,
                          "Set Base: Tremorsense": 1138,
                          "Set Base: Truesight": 1139,
                          "Size": 1140,
                          "Size: Gargantuan": 1141,
                          "Size: Huge": 1142,
                          "Size: Large": 1143,
                          "Size: Medium": 1144,
                          "Size: Small": 1145,
                          "Size: Tiny": 1146,
                          "Speed Reduction": 1147,
                          "Speed Reduction: Impose": 1148,
                          "Speed Reduction: Remove": 1149,
                          "Spell Slot Increase": 1150,
                          "Spell Slot Increase: Bard": 1151,
                          "Spell Slot Increase: Cleric": 1152,
                          "Spell Slot Increase: Druid": 1153,
                          "Spell Slot Increase: Paladin": 1154,
                          "Spell Slot Increase: Ranger": 1155,
                          "Spell Slot Increase: Sorcerer": 1156,
                          "Spell Slot Increase: Warlock": 1157,
                          "Spell Slot Increase: Wizard": 1158,
                          "Stacking Bonus": 1159,
                          "Stacking Bonus: Charisma Score": 1160,
                          "Stacking Bonus: Constitution Score": 1161,
                          "Stacking Bonus: Dexterity Score": 1162,
                          "Stacking Bonus: Intelligence Score": 1163,
                          "Stacking Bonus: Strength Score": 1164,
                          "Stacking Bonus: Wisdom Score": 1165,
                          "Stealth Disadvantage": 1166,
                          "Stealth Disadvantage: Impose": 1167,
                          "Stealth Disadvantage: Remove": 1168,
                          "Twice Proficiency": 1169,
                          "Twice Proficiency: Ability Checks": 1170,
                          "Twice Proficiency: Acrobatics": 1171,
                          "Twice Proficiency: Alchemist Supplies": 1172,
                          "Twice Proficiency: Animal Handling": 1173,
                          "Twice Proficiency: Arcana": 1174,
                          "Twice Proficiency: Athletics": 1175,
                          "Twice Proficiency: Bagpipes": 1176,
                          "Twice Proficiency: Battleaxe": 1177,
                          "Twice Proficiency: Blowgun": 1178,
                          "Twice Proficiency: Breastplate": 1179,
                          "Twice Proficiency: Brewer Supplies": 1180,
                          "Twice Proficiency: Calligrapher Supplies": 1181,
                          "Twice Proficiency: Carpenter Tools": 1182,
                          "Twice Proficiency: Cartographer Tools": 1183,
                          "Twice Proficiency: Chain Mail": 1184,
                          "Twice Proficiency: Chain Shirt": 1185,
                          "Twice Proficiency: Charisma Ability Checks": 1186,
                          "Twice Proficiency: Charisma Saving Throws": 1187,
                          "Twice Proficiency: Choose a Bard Skill": 1188,
                          "Twice Proficiency: Choose a Saving Throw": 1189,
                          "Twice Proficiency: Club": 1190,
                          "Twice Proficiency: Cobbler Tools": 1191,
                          "Twice Proficiency: Constitution Ability Checks": 1192,
                          "Twice Proficiency: Constitution Saving Throws": 1193,
                          "Twice Proficiency: Cook Utensils": 1194,
                          "Twice Proficiency: Crossbow": 1195,
                          "Twice Proficiency: Crossbow": 1196,
                          "Twice Proficiency: Crossbow": 1197,
                          "Twice Proficiency: Dagger": 1198,
                          "Twice Proficiency: Dart": 1199,
                          "Twice Proficiency: Deception": 1200,
                          "Twice Proficiency: Dexterity Ability Checks": 1201,
                          "Twice Proficiency: Dexterity Attacks": 1202,
                          "Twice Proficiency: Dexterity Saving Throws": 1203,
                          "Twice Proficiency: Dice Set": 1204,
                          "Twice Proficiency: Disguise Kit": 1205,
                          "Twice Proficiency: Dragonchess Set": 1206,
                          "Twice Proficiency: Drum": 1207,
                          "Twice Proficiency: Dulcimer": 1208,
                          "Twice Proficiency: Flail": 1209,
                          "Twice Proficiency: Flute": 1210,
                          "Twice Proficiency: Forgery Kit": 1211,
                          "Twice Proficiency: Glaive": 1212,
                          "Twice Proficiency: Glassblower Tools": 1213,
                          "Twice Proficiency: Greataxe": 1214,
                          "Twice Proficiency: Greatclub": 1215,
                          "Twice Proficiency: Greatsword": 1216,
                          "Twice Proficiency: Halberd": 1217,
                          "Twice Proficiency: Half Plate": 1218,
                          "Twice Proficiency: Handaxe": 1219,
                          "Twice Proficiency: Heavy Armor": 1220,
                          "Twice Proficiency: Herbalism Kit": 1221,
                          "Twice Proficiency: Hide": 1222,
                          "Twice Proficiency: History": 1223,
                          "Twice Proficiency: Horn": 1224,
                          "Twice Proficiency: Improvised Weapons": 1225,
                          "Twice Proficiency: Initiative": 1226,
                          "Twice Proficiency: Insight": 1227,
                          "Twice Proficiency: Intelligence Ability Checks": 1228,
                          "Twice Proficiency: Intelligence Saving Throws": 1229,
                          "Twice Proficiency: Intimidation": 1230,
                          "Twice Proficiency: Investigation": 1231,
                          "Twice Proficiency: Javelin": 1232,
                          "Twice Proficiency: Jeweler Tools": 1233,
                          "Twice Proficiency: Lance": 1234,
                          "Twice Proficiency: Leather": 1235,
                          "Twice Proficiency: Leatherworker Tools": 1236,
                          "Twice Proficiency: Light Armor": 1237,
                          "Twice Proficiency: Light Hammer": 1238,
                          "Twice Proficiency: Longbow": 1239,
                          "Twice Proficiency: Longsword": 1240,
                          "Twice Proficiency: Lute": 1241,
                          "Twice Proficiency: Lyre": 1242,
                          "Twice Proficiency: Mace": 1243,
                          "Twice Proficiency: Martial Weapons": 1244,
                          "Twice Proficiency: Mason Tools": 1245,
                          "Twice Proficiency: Maul": 1246,
                          "Twice Proficiency: Medicine": 1247,
                          "Twice Proficiency: Medium Armor": 1248,
                          "Twice Proficiency: Melee Attacks": 1249,
                          "Twice Proficiency: Mithril Plate Armor": 1250,
                          "Twice Proficiency: Morningstar": 1251,
                          "Twice Proficiency: Nature": 1252,
                          "Twice Proficiency: Navigator Tools": 1253,
                          "Twice Proficiency: Net": 1254,
                          "Twice Proficiency: Padded": 1255,
                          "Twice Proficiency: Painter Supplies": 1256,
                          "Twice Proficiency: Pan Flute": 1257,
                          "Twice Proficiency: Perception": 1258,
                          "Twice Proficiency: Performance": 1259,
                          "Twice Proficiency: Pike": 1260,
                          "Twice Proficiency: Plate": 1261,
                          "Twice Proficiency: Playing Card Set": 1262,
                          "Twice Proficiency: Poisoner Kit": 1263,
                          "Twice Proficiency: Potter Tools": 1264,
                          "Twice Proficiency: Quarterstaff": 1265,
                          "Twice Proficiency: Ranged Attacks": 1266,
                          "Twice Proficiency: Rapier": 1267,
                          "Twice Proficiency: Religion": 1268,
                          "Twice Proficiency: Ring Mail": 1269,
                          "Twice Proficiency: Saving Throws": 1270,
                          "Twice Proficiency: Scale Mail": 1271,
                          "Twice Proficiency: Scimitar": 1272,
                          "Twice Proficiency: Self": 1273,
                          "Twice Proficiency: Shawm": 1274,
                          "Twice Proficiency: Shields": 1275,
                          "Twice Proficiency: Shortbow": 1276,
                          "Twice Proficiency: Shortsword": 1277,
                          "Twice Proficiency: Sickle": 1278,
                          "Twice Proficiency: Simple Weapon": 1279,
                          "Twice Proficiency: Sleight of Hand": 1280,
                          "Twice Proficiency: Sling": 1281,
                          "Twice Proficiency: Smith Tools": 1282,
                          "Twice Proficiency: Spear": 1283,
                          "Twice Proficiency: Spell Attacks": 1284,
                          "Twice Proficiency: Splint": 1285,
                          "Twice Proficiency: Stealth": 1286,
                          "Twice Proficiency: Steel Shield": 1287,
                          "Twice Proficiency: Strength Ability Checks": 1288,
                          "Twice Proficiency: Strength Attacks": 1289,
                          "Twice Proficiency: Strength Saving Throws": 1290,
                          "Twice Proficiency: Studded Leather": 1291,
                          "Twice Proficiency: Survival": 1292,
                          "Twice Proficiency: Thieves Tools": 1293,
                          "Twice Proficiency: Three-Dragon Ante Set": 1294,
                          "Twice Proficiency: Tinker Tools": 1295,
                          "Twice Proficiency: Trident": 1296,
                          "Twice Proficiency: Vehicles (Land)": 1297,
                          "Twice Proficiency: Vehicles (Water)": 1298,
                          "Twice Proficiency: Viol": 1299,
                          "Twice Proficiency: War Pick": 1300,
                          "Twice Proficiency: Warhammer": 1301,
                          "Twice Proficiency: Weaver Tools": 1302,
                          "Twice Proficiency: Whip": 1303,
                          "Twice Proficiency: Wisdom Ability Checks": 1304,
                          "Twice Proficiency: Wisdom Saving Throws": 1305,
                          "Twice Proficiency: Woodcarver Tools": 1306,
                          "Vulnerability": 1307,
                          "Vulnerability: Acid": 1308,
                          "Vulnerability: All": 1309,
                          "Vulnerability: Bludgeoning": 1310,
                          "Vulnerability: Cold": 1311,
                          "Vulnerability: Fire": 1312,
                          "Vulnerability: Force": 1313,
                          "Vulnerability: Lightning": 1314,
                          "Vulnerability: Necrotic": 1315,
                          "Vulnerability: Piercing": 1316,
                          "Vulnerability: Poison": 1317,
                          "Vulnerability: Psychic": 1318,
                          "Vulnerability: Radiant": 1319,
                          "Vulnerability: Slashing": 1320,
                          "Vulnerability: Thunder": 1321,
                          "Weapon Property": 1322,
                          "Weapon Property: Finesse": 1323,
                          "Weapon Property: Heavy": 1324,
                          "Weapon Property: Light": 1325,
                          "Weapon Property: Loading": 1326,
                          "Weapon Property: Range": 1327,
                          "Weapon Property: Reach": 1328,
                          "Weapon Property: Thrown": 1329,
                          "Weapon Property: Two-Handed": 1330,
                          "Weapon Property: Versatile": 1331,
                          }


# <F> Fill_In_Item
def Fill_In_Item(lines):
    item = {"name": "",
            "ttrpg": "DND5E",
            "rarity": "",
            "renowned_quality": "",
            "requires_attunement": False,
            "has_charges": False,
            "is_cursed": False,
            "cost": "",
            "weight": "",
            "description": "",
            "image_url": "",
            "source_id": 5,
            "magic_bonus_plus_1": False,
            "magic_bonus_plus_2": False,
            "magic_bonus_plus_3": False,
            "description_notes": ""
            }
    count_three_dashes = 0
    string_description = ""

    for line in lines:
        if line.startswith("# "):
            item["name"] = line.replace("#", "").replace("'", "''").strip()
        elif line.startswith("rarity:"):
            item["rarity"] = line.replace("rarity:", "").replace("'", "''").strip()
        elif line.startswith("renowned_quality:"):
            item["renowned_quality"] = line.replace("renowned_quality:", "").replace("'", "''").strip()
        elif line.startswith("req_attunement:"):
            if "yes" in line.lower():
                item["requires_attunement"] = True
        elif line.startswith("is_cursed:"):
            if "yes" in line.lower():
                item["is_cursed"] = True
        elif line.startswith("Notes:"):
            item["description_notes"] = line.replace("Notes:", "").replace("'", "''").lower().strip()
        elif line.startswith("!["):
            continue
        elif "---" in line and count_three_dashes <= 3:
            count_three_dashes += 1
        elif count_three_dashes >= 3:
            string_description += line.replace("'", "''").replace("**", "").replace("_", "").replace("[[", "").replace(
                "]]", "") + "\n"

    item["description"] = string_description.rstrip("\n")

    return item


# RUN ====================================================
Pars_Document(file)
